## Translation time: 2024-03-04T06:44:00.523569Z
## Translation job ID: a86d938d-fa65-424d-bf4e-0008985e1778
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_TBOS/Tables/Stage_NTTARawTransactions.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS_STAGE_FULL.TranProcessing_NTTARawTransactions
(
  txnid INT64 NOT NULL,
  sourcesystem STRING,
  metadatarecordtype STRING,
  metadatapublishtime DATETIME,
  metadatarecordnumber STRING,
  recordtype STRING,
  recordnumber INT64,
  timestamp DATETIME,
  facilitycode STRING,
  plazacode STRING,
  lane INT64,
  logontimestamp DATETIME,
  lanemode INT64,
  revenuevehicleclass INT64,
  revenueaxles INT64,
  indicatedvehicleclass INT64,
  indicatedaxles INT64,
  forwardaxles INT64,
  reverseaxles INT64,
  vehiclespeed INT64,
  fareamount NUMERIC(31, 2),
  straddleindication INT64,
  entryloopactivation INT64,
  midlaneloopactivation INT64,
  exitloopactivation INT64,
  imagerequested INT64,
  paymenttype INT64,
  tagidnumber INT64,
  tagagency INT64,
  tagstatus INT64,
  tagclass INT64,
  iagtagvehicletype INT64,
  iagtagvehicleaxles INT64,
  iagtagvehicleweight INT64,
  iagtagdualreartires INT64,
  iagtagrevenuetype INT64,
  iagtagcommissionflag INT64,
  tagreads INT64,
  violationserialnumber INT64,
  vestimestamp DATETIME,
  standbymodestatus INT64,
  acmstatus INT64,
  avireaderstatus INT64,
  dualtiresensor INT64,
  failovermodulestatus INT64,
  redundantlcstatus INT64,
  avcstatus INT64,
  treadlestatus INT64,
  scannerseparatorstatus INT64,
  vesstatus INT64,
  attendantterminalstatus INT64,
  facilityserveravistatusdownload INT64,
  facilityservertransactionupload INT64,
  ups INT64,
  digitaliointerface INT64,
  receiptprinter INT64,
  tvlbatchid INT64,
  faretableid INT64,
  taglowbattery INT64,
  estimatedaxlecount INT64,
  auxiliaryloopactivation INT64,
  maintenanceoverride INT64,
  rawstringdata STRING,
  isunabletoparse STRING,
  ismalformed STRING,
  hostbosid INT64,
  disposition STRING,
  invoicestatus STRING,
  equipmentcode INT64,
  deviceinstance INT64,
  statuscode INT64,
  conditionstate INT64,
  messagetext STRING,
  logofftimestamp DATETIME,
  tagtimestamp DATETIME,
  tagstring STRING,
  createddate DATETIME NOT NULL,
  createduser STRING NOT NULL,
  updateddate DATETIME NOT NULL,
  updateduser STRING NOT NULL,
  lnd_updatedate DATETIME,
  lnd_updatetype STRING,
  src_changedate DATETIME
)
cluster by txnid
;