## Translation time: 2024-03-04T06:44:00.523569Z
## Translation job ID: a86d938d-fa65-424d-bf4e-0008985e1778
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_TBOS/Tables/Stage_BOS_IOP_OutboundTransactions.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS_STAGE_FULL.IOP_BOS_IOP_OutboundTransactions
(
  bosioptransactionid INT64 NOT NULL,
  iopid INT64,
  transactiontypeid INT64 NOT NULL,
  tagtype STRING,
  transactiondate DATETIME NOT NULL,
  agencyid STRING,
  entryplaza INT64,
  entrylane INT64,
  tagstatus STRING,
  licencenumber STRING,
  licensestate STRING,
  exitplaza INT64 NOT NULL,
  exitlane INT64 NOT NULL,
  transactionstatus STRING,
  reconcilitionfileid INT64,
  tollamount NUMERIC(31, 2) NOT NULL,
  acceptedamount NUMERIC(31, 2),
  iscorrected INT64 NOT NULL,
  discountamount NUMERIC(31, 2),
  tptripid INT64,
  tagserialnumber STRING,
  vehicleclass STRING,
  tripmethod STRING,
  posteddate DATETIME,
  resubmitcount INT64,
  tranfileid INT64,
  facilitycode STRING,
  plazacode STRING,
  lanecode STRING,
  entrytripdatetime DATETIME,
  exittripdatetime DATETIME,
  platetype STRING,
  facilitydesc STRING,
  entryplazadesc STRING,
  exitplazadesc STRING,
  entrytripdatetimewithtimezone TIMESTAMP,
  exittripdatetimewithtimezone TIMESTAMP,
  licenseplatecountry STRING,
  violationserialnumber INT64,
  vestimestamp DATETIME,
  tagagencyid INT64,
  resubmitreasoncode STRING,
  correctionreasoncode STRING,
  transactionflatfee NUMERIC(31, 2),
  transactionpercentfee NUMERIC(31, 2),
  sourceofentry INT64,
  correctioncount INT64,
  sourcepkid INT64,
  recordcode STRING,
  accountagencyid STRING,
  adjustmentdatetime DATETIME,
  postingdisposition STRING,
  postingdispositionreason STRING,
  adjustmentresponsepayload STRING,
  homeagencyrefid INT64,
  spare1 STRING,
  spare2 STRING,
  spare3 STRING,
  spare4 STRING,
  spare5 STRING,
  othercorrectiondescription STRING,
  createddate DATETIME NOT NULL,
  createduser STRING,
  updateddate DATETIME NOT NULL,
  updateduser STRING,
  lnd_updatedate DATETIME,
  lnd_updatetype STRING,
  src_changedate DATETIME
)cluster by BOSIOPTransactionID
;