## Translation time: 2024-03-04T06:44:00.523569Z
## Translation job ID: a86d938d-fa65-424d-bf4e-0008985e1778
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_TBOS/Tables/Stage_IOPInboundRawTransactions.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS_STAGE_FULL.TranProcessing_IOPInboundRawTransactions
(
  txnid INT64 NOT NULL,
  fileid INT64,
  recordtype STRING,
  originalrecordtype STRING,
  transactionreferenceid STRING,
  exitdatetime STRING,
  facilityid STRING,
  facilitydescription STRING,
  exitplaza STRING,
  exitplazadescription STRING,
  exitlane STRING,
  entrydatetime STRING,
  entryplaza STRING,
  entryplazadescription STRING,
  entrylane STRING,
  tagagencyid STRING,
  tagserialnumber STRING,
  tagstatus STRING,
  occupancyindicator STRING,
  vehicleclassification STRING,
  tollamount STRING,
  discountplan STRING,
  licenseplatecountry STRING,
  licenseplatestate STRING,
  licenseplatenumber STRING,
  licenseplatetype STRING,
  vehicleclassificationadjustmentflag STRING,
  systemmatchedflag STRING,
  resubmitcount STRING,
  resubmitreason STRING,
  reconciliationhomeagencyid STRING,
  homeagencyreferenceid STRING,
  postingdisposition STRING,
  posteddiscountplan STRING,
  postedamount STRING,
  posteddatetime STRING,
  transactionflatfee STRING,
  transactionpercentfee STRING,
  correctiondatetime STRING,
  correctionreason STRING,
  othercorrectiondescription STRING,
  correctioncount STRING,
  spare1 STRING,
  spare2 STRING,
  spare3 STRING,
  spare4 STRING,
  spare5 STRING,
  correctionseqeunceno INT64,
  tptripid INT64,
  filetype STRING,
  hostbosid INT64,
  transactionstatusid INT64,
  reconfileid INT64,
  uniquesequenceno INT64,
  awayagencyid STRING,
  sourcepkid INT64,
  sourcerawpkid INT64,
  createddate DATETIME NOT NULL,
  createduser STRING NOT NULL,
  updateddate DATETIME NOT NULL,
  updateduser STRING NOT NULL,
  lnd_updatedate DATETIME,
  lnd_updatetype STRING,
  src_changedate DATETIME
)
CLUSTER BY
txnid
;