## Translation time: 2024-03-04T06:44:00.523569Z
## Translation job ID: a86d938d-fa65-424d-bf4e-0008985e1778
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_TBOS/Tables/Stage_TP_Trips.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS_STAGE_FULL.TollPlus_TP_Trips
(
  tptripid INT64 NOT NULL,
  entry_tolltxnid INT64 NOT NULL,
  exit_tolltxnid INT64 NOT NULL,
  entrytripdatetime DATETIME,
  entrytripdatetimeutc DATETIME,
  exittripdatetime DATETIME,
  exittripdatetimeutc DATETIME,
  tripidentmethod STRING,
  tripchargetype STRING,
  entrylaneid INT64,
  entryplazaid INT64,
  exitlaneid INT64,
  exitplazaid INT64,
  lanetype STRING,
  vehiclenumber STRING,
  vehicleid INT64,
  vehiclestate STRING,
  vehicleclass STRING,
  tagrefid STRING,
  tollamount NUMERIC(31, 2),
  receivedtollamount NUMERIC(31, 2),
  feeamounts NUMERIC(31, 2),
  discountsamount NUMERIC(31, 2),
  outstandingamount NUMERIC(31, 2),
  tripstageid INT64,
  tripstatusid INT64,
  tripstatusdate DATETIME,
  posteddate DATETIME,
  irtripid INT64,
  paymentstatusid INT64,
  reasoncode STRING,
  sourcetripid INT64,
  tagvehicleclass STRING,
  tagtype STRING,
  transactiontypeid INT64,
  platetype STRING,
  ipstransactionid INT64,
  pbmtollamount NUMERIC(31, 2),
  avitollamount NUMERIC(31, 2),
  originalpbmtollamount NUMERIC(31, 2),
  originalavitollamount NUMERIC(31, 2),
  licenseplatecountry STRING,
  locationid INT64,
  agencyid INT64,
  disposition STRING,
  receiveddate DATETIME,
  tagagency STRING,
  tagagencyid INT64,
  sourceofentry INT64,
  accountagencyid INT64,
  isimagereviewed INT64,
  sourcetxnid INT64,
  linkid INT64,
  tripwith STRING,
  isnonrevenue INT64 NOT NULL,
  txnrate STRING,
  transactionpostingtype STRING,
  sourceid INT64,
  sourcename STRING,
  acct_id INT64,
  ttxn_id INT64,
  createddate DATETIME NOT NULL,
  createduser STRING NOT NULL,
  updateddate DATETIME NOT NULL,
  updateduser STRING NOT NULL,
  lnd_updatedate DATETIME,
  lnd_updatetype STRING,
  src_changedate DATETIME
)Cluster by  tptripid
;