## Translation time: 2024-03-04T06:41:57.683170Z
## Translation job ID: 00dc6676-2c12-444a-b02a-71c7788bdc89
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/EDW_TRIPS/Tables/dbo_Dim_HabitualViolator.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS EDW_TRIPS.Dim_HabitualViolator
(
  hvid INT64 NOT NULL,
  customerid INT64 NOT NULL,
  vehicleid INT64,
  licenseplatestate STRING,
  licenseplatenumber STRING,
  hvstatuslookupid INT64,
  hvcurrentstatus STRING,
  hvterminationreason STRING,
  hvtransactioncount INT64,
  adminhearingcountyid INT64,
  adminhearingcountyname STRING,
  adminhearingstatusid INT64,
  adminheaderingstatus STRING,
  adminhearingreason STRING,
  adminhearingrequesteddate DATETIME,
  vehicleregistrationcountyid STRING,
  vehicleregistrationcountyname STRING,
  rovaddresscountyid STRING,
  rovaddresscountyname STRING,
  hvfirstqualifiedtrandate DATETIME,
  hvlastqualifiedtrandate DATETIME,
  hvdeterminationdate DATETIME,
  latesthvdeterminationlettermaileddate DATETIME,
  latesthvdeterminationletterdelivereddate DATETIME,
  earliesthvdeterminationlettermaileddate DATETIME,
  earliesthvdeterminationletterdelivereddate DATETIME,
  hvterminationdate DATETIME,
  latesthvterminationlettermaileddate DATETIME,
  latesthvterminationletterdeliverydate DATETIME,
  earliesthvterminationlettermaileddate DATETIME,
  earliesthvterminationletterdelivereddate DATETIME,
  earliestvrbstatusid INT64,
  earliestvrbstatusdescription STRING,
  earliestvrbremovallookupid INT64,
  earliestvrbremovallookupdescription STRING,
  earliestvrbrequesteddate DATETIME,
  earliestvrbplaceddate DATETIME,
  earliestvrbremoveddate DATETIME,
  latestvrbstatusid INT64,
  latestvrbstatusdescription STRING,
  latestvrbremovallookupid INT64,
  latestvrbremovallookupdescription STRING,
  latestvrbrequesteddate DATETIME,
  latestvrbplaceddate DATETIME,
  latestvrbremoveddate DATETIME,
  latestvrblettermaileddate DATETIME,
  latestvrbletterdelivereddate DATETIME,
  earliestvrblettermaileddate DATETIME,
  earliestvrbletterdelivereddate DATETIME,
  vbremoveddate DATETIME,
  removalreasonid INT64,
  removalreasoncode STRING,
  vbapplieddate DATETIME,
  latestvehiclebanlettermaileddate DATETIME,
  latestvehiclebanletterdelivereddate DATETIME,
  earliestvehiclebanlettermaileddate DATETIME,
  earliestvehiclebanletterdelivereddate DATETIME,
  scheduledhearingdate DATETIME,
  earliestcitationdate DATETIME,
  latestcitationdate DATETIME,
  hvtollsdue NUMERIC(31, 2),
  hvfeesdue NUMERIC(31, 2),
  hvcurrentdue NUMERIC(31, 2),
  mbscurrentdue NUMERIC(31, 2),
  edw_updatedate DATETIME NOT NULL
)
CLUSTER BY hvid
;