-- Translation time: 2024-07-11T07:10:16.441155Z
-- Translation job ID: 01f97d19-b914-463a-8c9e-73c23536d6e1
-- Source: gs://ntta-gcp-poc-source-code-scripts/transpiled_ddl_tmp/ITEM_90_NEW_APS/dbo.Fact_Invoice.dsql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS  EDW_TRIPS.Fact_Invoice
(
  invoicenumber INT64,
  firstinvoiceid INT64,
  currentinvoiceid INT64,
  customerid INT64,
  testcasefailedflag INT64,
  migratedflag INT64 NOT NULL,
  vtollflag INT64 NOT NULL,
  unassignedflag INT64 NOT NULL,
  agestageid INT64,
  collectionstatusid INT64,
  currmbsid INT64,
  vehicleid INT64,
  edw_invoicestatusid INT64,
  paymentplanid INT64 NOT NULL,
  zipcashdate DATE,
  firstnoticedate DATE,
  secondnoticedate DATE,
  thirdnoticedate DATE,
  legalactionpendingdate DATE,
  citationdate DATE,
  duedate DATE,
  currmbsgenerateddate DATE,
  firstpaymentdate DATE,
  lastpaymentdate DATE,
  firstfeepaymentdate DATE,
  lastfeepaymentdate DATE,
  primarycollectionagencydate DATE,
  secondarycollectionagencydate DATE,
  txncnt INT64,
  vtolltxncnt INT64,
  excusedtxncnt INT64,
  unassignedtxncnt INT64,
  paidtxncnt INT64,
  nooftimessenttoprimary INT64,
  nooftimessenttosecondary INT64,
  paymentchannel STRING,
  pos STRING,
  primarycollectionagency STRING,
  secondarycollectionagency STRING,
  invoiceamount NUMERIC(31, 2),
  pbmtollamount NUMERIC(31, 2),
  avitollamount NUMERIC(31, 2),
  premiumamount NUMERIC(31, 2),
  tolls NUMERIC(31, 2),
  fnfees NUMERIC(31, 2),
  snfees NUMERIC(31, 2),
  expectedamount NUMERIC(31, 2),
  tollsadjusted NUMERIC(31, 2),
  fnfeesadjusted NUMERIC(31, 2),
  snfeesadjusted NUMERIC(31, 2),
  adjustedamount NUMERIC(31, 2),
  adjustedexpectedtolls NUMERIC(31, 2),
  adjustedexpectedfnfees NUMERIC(31, 2),
  adjustedexpectedsnfees NUMERIC(31, 2),
  adjustedexpectedamount NUMERIC(31, 2),
  tollspaid NUMERIC(31, 2),
  fnfeespaid NUMERIC(31, 2),
  snfeespaid NUMERIC(31, 2),
  paidamount NUMERIC(31, 2),
  tolloutstandingamount NUMERIC(31, 2),
  fnfeesoutstandingamount NUMERIC(31, 2),
  snfeesoutstandingamount NUMERIC(31, 2),
  outstandingamount NUMERIC(31, 2),
  edw_update_date DATETIME NOT NULL
)
;
