CREATE TABLE IF NOT EXISTS `LND_SHARED_DATA.Exception_Detail_ACT0002`
(recordtype	STRING,	
submissiondate	DATE,	
pidno INTEGER,	
pidshortname STRING,	
submissionno	STRING,	
recordno	INTEGER,	
entitytype	STRING,	
entityno	INTEGER,	
presentmentcurrency	STRING,	
merchantorderno	STRING,	
rdfino	STRING,	
accountno STRING,	
expirationdate	STRING,	
amount	NUMERIC,	
mop	STRING,	
actioncode	STRING,	
authdate	STRING,	
authcode	STRING,	
authresponsecode	STRING,	
traceno	STRING,	
consumercountrycode STRING,	
category STRING,	
mcc	INTEGER,	
rejectcode	INTEGER,	
submissionstatus	STRING,	
lnd_updatedate	DATETIME
); 