CREATE TABLE IF NOT EXISTS `LND_SHARED_DATA.Stage_Exception_Detail_ACT0002`
(recordtype	STRING,	
submissiondate	STRING,	
pidno STRING,	
pidshortname STRING,	
submissionno	STRING,	
recordno	STRING,	
entitytype	STRING,	
entityno	STRING,	
presentmentcurrency	STRING,	
merchantorderno	STRING,	
rdfino	STRING,	
accountno STRING,	
expirationdate	STRING,	
amount	STRING,	
mop	STRING,	
actioncode	STRING,	
authdate	STRING,	
authcode	STRING,	
authresponsecode	STRING,	
traceno	STRING,	
consumercountrycode STRING,	
category STRING,	
mcc	STRING,	
rejectcode	STRING,	
submissionstatus	STRING,	
lnd_updatedate	STRING	
);