## Translation time: 2024-03-21T20:56:06.764423Z
## Translation job ID: e212c5d3-a7fa-4886-93b1-cb3be341e70a
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/EDW_RITE/Tables/dbo_TEMP.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS EDW_RITE.Temp
(
  violator_id INT64 NOT NULL,
  date_batch_produced DATE,
  vbi_invoice_id INT64 NOT NULL,
  vb_inv_date DATE,
  zi_stage_id INT64 NOT NULL,
  invoice_stage_id INT64,
  vbi_status STRING NOT NULL,
  converted_date DATE,
  viol_invoice_id INT64 NOT NULL,
  viol_inv_status STRING NOT NULL,
  `3nnp_inv_date` DATE,
  first_paid_date DATE,
  paid_date DATE,
  paid_date_list DATE,
  paid_date_count INT64 NOT NULL,
  first_pos_id INT64 NOT NULL,
  pos_id INT64 NOT NULL,
  pos_name_list STRING,
  pos_count INT64 NOT NULL,
  payment_source_code STRING NOT NULL,
  delivery_code STRING NOT NULL,
  ca_inv_status STRING NOT NULL,
  first_ca_company_id INT64 NOT NULL,
  ca_company_id INT64 NOT NULL,
  ca_company_name_list STRING,
  ca_company_count INT64 NOT NULL,
  first_ca_file_gen_date DATE NOT NULL,
  ca_file_gen_date DATE NOT NULL,
  ca_file_gen_date_list DATE,
  ca_file_gen_date_count INT64 NOT NULL,
  first_citation_nbr STRING,
  citation_nbr STRING,
  citation_nbr_list STRING,
  citation_nbr_count INT64 NOT NULL,
  first_ca_acct_id INT64 NOT NULL,
  ca_acct_id INT64 NOT NULL,
  ca_acct_id_list INT64,
  ca_acct_id_count INT64 NOT NULL,
  court_action_mail_date DATETIME NOT NULL,
  dps_inv_status STRING NOT NULL,
  invoice_amt NUMERIC(33, 4),
  toll_due NUMERIC(33, 4),
  zi_late_fees BIGNUMERIC(57, 19),
  vi_late_fees NUMERIC(33, 4),
  admin_fee BIGNUMERIC(57, 19),
  admin_fee2 BIGNUMERIC(57, 19),
  amt_paid BIGNUMERIC(57, 19),
  close_out_eligibility_date DATE NOT NULL,
  close_out_status STRING NOT NULL,
  close_out_date DATE NOT NULL,
  close_out_type STRING NOT NULL,
  viol_count INT64,
  vehicle_class INT64,
  insert_date DATETIME NOT NULL
)
;
