## Translation time: 2024-03-21T20:56:06.764423Z
## Translation job ID: e212c5d3-a7fa-4886-93b1-cb3be341e70a
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/EDW_RITE/Tables/dbo_FACT_INVOICES_DATA_OLD.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS EDW_RITE.Fact_Invoices_Data_Old
(
  last_invoice_id INT64 NOT NULL,
  vbi_invoice_id INT64 NOT NULL,
  viol_invoice_id INT64 NOT NULL,
  violator_id INT64,
  violator_addr_seq INT64,
  transactions_cnt INT64,
  toll_amount NUMERIC(31, 2),
  fees_amount NUMERIC(31, 2),
  legacy_transactions_cnt INT64,
  legacy_toll_amount NUMERIC(31, 2),
  legacy_fees_amount NUMERIC(31, 2),
  vbi_status STRING,
  vb_invoice_date DATETIME,
  vb_invoice_amt NUMERIC(31, 2),
  vb_invoice_amt_disc NUMERIC(31, 2),
  vb_late_fee_amount NUMERIC(31, 2),
  vb_past_due_amount NUMERIC(31, 2),
  vb_invoice_amt_paid NUMERIC(31, 2),
  vbb_ln_batch_id INT64,
  vbb_batch_id INT64,
  vb_date_excused DATETIME,
  vb_excused_by STRING,
  vb_excused_reason STRING,
  vb_due_date DATETIME,
  vb_closed_date DATETIME,
  vb_date_created DATETIME,
  vb_date_modified DATETIME,
  vb_conversion_date DATETIME,
  vb_source_code STRING,
  vb_mail_date DATETIME,
  viol_inv_status STRING,
  viol_invoice_date DATETIME,
  viol_invoice_amt NUMERIC(31, 2),
  viol_invoice_amt_paid NUMERIC(31, 2),
  viol_invoice_amt_disc NUMERIC(31, 2),
  viol_inv_admin_fee NUMERIC(31, 2),
  viol_inv_admin_fee2 NUMERIC(31, 2),
  viol_fine_amount NUMERIC(31, 2),
  viol_inv_batch_id NUMERIC(29),
  viol_inv_date_excused DATETIME,
  viol_inv_excused_by STRING,
  viol_inv_excused_reason STRING,
  viol_inv_curr_due_date DATETIME,
  viol_inv_status_date DATETIME,
  viol_inv_date_modified DATETIME,
  viol_inv_closed_date DATETIME,
  viol_inv_source_code STRING,
  viol_inv_dps_date DATETIME,
  viol_inv_dps_reject_date DATETIME,
  viol_inv_date_created DATETIME,
  viol_inv_gl_status STRING,
  viol_inv_is_vtoll STRING,
  viol_inv_is_vea STRING,
  ca_inv_status STRING,
  dps_inv_status STRING,
  close_out_eligibility_date DATETIME,
  close_out_status STRING,
  close_out_date DATETIME,
  close_out_type STRING
)
cluster by VBI_INVOICE_ID,VIOL_INVOICE_ID
;
