## Translation time: 2024-03-21T20:56:06.764423Z
## Translation job ID: e212c5d3-a7fa-4886-93b1-cb3be341e70a
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/EDW_RITE/Tables/dbo_FACT_UVS_LANE_VIOL_STAGE.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS EDW_RITE.Fact_Uvs_Lane_Viol_Stage
(
  lane_file_id STRING,
  lane_viol_id NUMERIC(29) NOT NULL,
  viol_date DATE,
  axle_count INT64,
  lane_viol_status STRING NOT NULL,
  lane_review_status STRING NOT NULL,
  violation_code INT64,
  viol_created STRING,
  license_plate_id INT64,
  lic_plate_nbr STRING,
  lic_plate_state STRING,
  review_date DATE,
  viol_reject_type STRING,
  toll_due NUMERIC(31, 2),
  toll_paid NUMERIC(31, 2),
  violation_id INT64,
  status_date DATE,
  manual_viol_flag INT64,
  driver_lic_state STRING,
  violator_id NUMERIC(29),
  viol_status STRING,
  transaction_id NUMERIC(29),
  disposition STRING,
  vtoll_send_date DATE,
  ttxn_id INT64,
  lvl_tvl STRING,
  posted_date DATE,
  posted_revenue NUMERIC(31, 2),
  iop_rev NUMERIC(31, 2),
  toll_rev NUMERIC(31, 2),
  vtoll_rev NUMERIC(31, 2),
  iop_flag INT64,
  source_code STRING,
  acct_id INT64,
  tag_id STRING,
  agency_id STRING,
  dmv_sts STRING,
  txn_name STRING,
  not_trans_review_status_abbrev STRING,
  vbi_invoice_id INT64,
  viol_invoice_id INT64,
  payment_date DATE,
  deposit_date DATE,
  split_amount NUMERIC(31, 2),
  fleet_flag INT64,
  fees_paid NUMERIC(31, 2),
  amt_paid NUMERIC(31, 2),
  vbi_invoice_date DATE,
  vbi_status STRING,
  vi_invoice_date DATE,
  viol_inv_status STRING,
  invoice_stage_id INT64,
  excused_reason STRING,
  date_excused DATE,
  excused_by STRING
)
;
