## Translation time: 2024-03-04T06:44:00.523569Z
## Translation job ID: a86d938d-fa65-424d-bf4e-0008985e1778
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_TBOS/Tables/Stage_DMVResponse.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS_STAGE_CDC.TollPlus_DMVResponse
(
  dmvresponseid INT64 NOT NULL,
  fileid INT64 NOT NULL,
  original_input_request STRING,
  currentlicense STRING,
  plateageyears STRING,
  reg_classcode STRING,
  plate_type_description STRING,
  countyname STRING,
  vehicleyear INT64,
  vehiclemake STRING,
  vehicle_body_style STRING,
  vehicleclass STRING,
  previousowner STRING,
  ownername_line1 STRING,
  ownername_line2 STRING,
  owneraddress_line1 STRING,
  owneraddress_line2 STRING,
  ownercity STRING,
  ownerstate STRING,
  ownerzip STRING,
  expiration_mm INT64,
  expiration_yyyy INT64,
  previous_expiration_yyyy INT64,
  vehiclemodel STRING,
  registration_issuedate DATETIME,
  vehicle_solddate DATETIME,
  receiveddate DATETIME,
  endeffectivedate DATETIME,
  inputlicensenumber STRING,
  vehiclevin STRING,
  vehiclebodyvin STRING,
  stickernumber STRING,
  previouslicense STRING,
  renew_receipt_name STRING,
  renew_receipt_addr_line1 STRING,
  renew_receipt_addr_line2 STRING,
  renew_receipt_addr_city STRING,
  renew_receipt_addr_state STRING,
  renew_receipt_addr_zip STRING,
  rts_titlenumber STRING,
  rts_titledate DATETIME,
  surrenerdate DATETIME,
  vehicle_location_addr STRING,
  vehicle_location_addr2 STRING,
  vehicle_location_city STRING,
  vehicle_location_state STRING,
  vehicle_location_zip STRING,
  primary_color_code STRING,
  primary_color STRING,
  secondary_color_code STRING,
  secondary_color STRING,
  unused_extra_space STRING,
  vehiclestate STRING,
  ownerzip2 STRING,
  renew_receipt_addr_zip2 STRING,
  owner_middlename STRING,
  owner_suffix STRING,
  regexpirationdate DATETIME,
  providername STRING,
  createddate DATETIME NOT NULL,
  createduser STRING,
  updateddate DATETIME NOT NULL,
  updateduser STRING,
  lnd_updatedate DATETIME,
  lnd_updatetype STRING,
  src_changedate DATETIME
)
CLUSTER BY dmvresponseid
;