-- Translation time: 2024-06-04T08:04:57.852399Z
-- Translation job ID: d189ef38-1420-4658-96a7-29624b482bd7
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_VPS/Tables/HV_OWNER_HV_FACT.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_VPS.Hv_Owner_Hv_Fact
(
  violator_id FLOAT64 NOT NULL,
  vid_seq FLOAT64 NOT NULL,
  hv_flag STRING,
  hv_designation_start_date DATE,
  hv_designation_end_date DATE,
  first_qualified_tran_date DATE,
  last_qualified_tran_date DATE,
  qualified_transactions_count FLOAT64,
  qualified_invoices_count FLOAT64,
  admin_hearing_county STRING,
  lic_plate_nbr STRING,
  lic_plate_state STRING,
  vehicle_year STRING,
  vehicle_make STRING,
  vehicle_model STRING,
  vin STRING,
  violator_fname STRING,
  violator_lname STRING,
  violator_fname2 STRING,
  violator_lname2 STRING,
  address1 STRING,
  address2 STRING,
  city STRING,
  state STRING,
  zip_code STRING,
  plus4 STRING,
  addr_status STRING,
  phone_nbr STRING,
  email_addr STRING,
  driver_lic_nbr STRING,
  driver_lic_state STRING,
  driver_lic_nbr2 STRING,
  driver_lic_state2 STRING,
  dmv_records_drec_id FLOAT64,
  docno STRING,
  registration_county_texas STRING,
  registration_date_next_month STRING,
  registration_date_next_year STRING,
  hv_q_first_tran_date DATE,
  hv_q_last_tran_date DATE,
  hv_q_amount_due FLOAT64,
  hv_q_tolls_due FLOAT64,
  hv_q_fees_due FLOAT64,
  hv_q_trans_fine_amount_due FLOAT64,
  hv_q_transactions_count FLOAT64,
  hv_q_invoice_count FLOAT64,
  vb_amount_due FLOAT64,
  vb_tolls_due FLOAT64,
  vb_late_fees_due FLOAT64,
  vb_transactions_count FLOAT64,
  vb_invoices_count FLOAT64,
  viol_amount_due FLOAT64,
  viol_tolls_due FLOAT64,
  viol_admin_fees_due FLOAT64,
  viol_trans_fine_amount_due FLOAT64,
  viol_transactions_count FLOAT64,
  viol_invoices_count FLOAT64,
  total_amount_due FLOAT64,
  total_tolls_due FLOAT64,
  total_fees_due FLOAT64,
  total_trans_fine_amount_due FLOAT64,
  total_transactions_count FLOAT64,
  total_invoices_count FLOAT64,
  hv_statements_count FLOAT64,
  ca_invoices_count FLOAT64,
  total_citation_count FLOAT64,
  date_created DATE,
  created_by STRING,
  date_modified DATE,
  modified_by STRING,
  last_update_type STRING NOT NULL,
  last_update_date DATETIME NOT NULL
)
;
