-- Translation time: 2024-06-04T08:04:57.852399Z
-- Translation job ID: d189ef38-1420-4658-96a7-29624b482bd7
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_VPS/Tables/VP_OWNER_LANE_VIOLATIONS.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_VPS.Vp_Owner_Lane_Violations
(
  lane_viol_id NUMERIC(29),
  lane_viol_status STRING,
  lc_plaza_nbr STRING,
  lc_lane_nbr STRING,
  viol_date DATETIME,
  time_nbr NUMERIC(29),
  sequence_nbr NUMERIC(29),
  lane_mode INT64,
  employee_id NUMERIC(29),
  vehicle_class INT64,
  axle_count INT64,
  violation_code INT64,
  unusual_code INT64,
  toll_due NUMERIC(31, 2),
  toll_paid NUMERIC(31, 2),
  agency_id INT64,
  tag_id STRING,
  tag_status INT64,
  vehicle_speed INT64,
  consec_prev_viol INT64,
  consec_follow_viol INT64,
  poss_false_trigger STRING,
  device_status INT64,
  fail_reason INT64,
  lic_plate_nbr STRING,
  ocr_nbr_confid INT64,
  lic_plate_state STRING,
  ocr_state_confid INT64,
  image_name STRING,
  roi_image_name STRING,
  image_loc STRING,
  image_archive_loc STRING,
  ocr_confid_cutoff INT64,
  state_confid_cutoff INT64,
  reviewed_by STRING,
  pre_audit_result STRING,
  audit_result STRING,
  created_date DATETIME,
  modified_date DATETIME,
  lane_abbrev STRING,
  ves_name STRING,
  sequence_nbr1 INT64,
  lane_controller_type STRING,
  review_status STRING,
  viol_reject_type STRING,
  review_date DATETIME,
  status_date DATETIME,
  viol_created STRING,
  review_user_id INT64,
  lc_facility_code STRING,
  plaza_code STRING,
  lane_code STRING,
  lic_plate_nbr_2 STRING,
  host_transaction_id NUMERIC(29),
  lane_id NUMERIC(29),
  ocr_plate_nbr STRING,
  ocr_plate_state STRING,
  dac_ocr_modified_date DATETIME,
  dac_ocr_plate_confid FLOAT64,
  dac_ocr_plate_nbr STRING,
  dac_ocr_plate_state STRING,
  source_server STRING,
  camera_lic_plate_nbr STRING,
  camera_lic_plate_state STRING,
  camera_lic_plate_confid INT64,
  transaction_file_detail_id NUMERIC(29),
  subscriber_id STRING,
  last_update_type STRING,
  last_update_date DATETIME
)
cluster by lane_viol_id
;
