CREATE TABLE IF NOT EXISTS LND_LG_VPS.Vp_Owner_Vb_Statements_Deleted (
    vbs_statement_id NUMERIC(29) NOT NULL,
    vba_account_id NUMERIC(29) NOT NULL,
    vbsb_batch_id NUMERIC(29) NOT NULL,
    vbs_statement_date DATETIME NOT NULL,
    vbs_generation_date DATETIME NOT NULL,
    vbs_payment_due_date DATETIME NOT NULL,
    vbs_amount_due NUMERIC(31, 2) NOT NULL,
    vbs_previous_balance NUMERIC(31, 2) NOT NULL,
    vbs_unpaid_balance NUMERIC(31, 2) NOT NULL,
    vbs_payments_total NUMERIC(31, 2) NOT NULL,
    vbs_tolls_total NUMERIC(31, 2) NOT NULL,
    vbs_inv_admin_fee_total NUMERIC(31, 2) NOT NULL,
    vbs_inv_admin_fee2_total NUMERIC(31, 2) NOT NULL,
    vbs_adjustments_total NUMERIC(31, 2) NOT NULL,
    vbs_first_name STRING,
    vbs_last_name STRING,
    vbs_license_plate STRING NOT NULL,
    vbs_lic_plate_state STRING NOT NULL,
    vbs_vehicle_make STRING,
    vbs_vehicle_model STRING,
    vbs_vehicle_year STRING,
    vbs_addr_viol_id NUMERIC(29) NOT NULL,
    vbs_addr_seq_id INT64 NOT NULL,
    vbs_billing_period_start DATETIME NOT NULL,
    vbs_billing_period_end DATETIME NOT NULL,
    vbs_statement_status STRING NOT NULL,
    vbs_toll_tag_savings NUMERIC(31, 2) NOT NULL,
    vbs_image_name STRING,
    vbs_image_path STRING,
    vbs_statement_notes STRING,
    date_created DATETIME NOT NULL,
    created_by STRING NOT NULL,
    date_modified DATETIME,
    modified_by STRING,
    vbs_first_name_2 STRING,
    vbs_last_name_2 STRING,
    vbs_unique_id NUMERIC(29),
    last_update_date DATETIME,
    last_update_type STRING
);