CREATE TABLE IF NOT EXISTS LND_LG_VPS.Vp_Owner_Vb_Invoices_Jn (
    sequence_id NUMERIC(29),
    jn_operation STRING NOT NULL,
    jn_oracle_user STRING NOT NULL,
    jn_datetime DATETIME NOT NULL,
    jn_appln STRING,
    jn_session BIGNUMERIC(38),
    vbi_invoice_id NUMERIC(29) NOT NULL,
    vbi_account_id NUMERIC(29),
    vbi_status STRING,
    vbb_batch_id NUMERIC(29),
    violator_id NUMERIC(29),
    violator_addr_seq INT64,
    invoice_date DATETIME,
    invoice_amount NUMERIC(31, 2),
    toll_amount NUMERIC(31, 2),
    late_fee_amount NUMERIC(31, 2),
    mail_fee_amount NUMERIC(31, 2),
    past_due_amount NUMERIC(31, 2),
    invoice_amt_disc NUMERIC(31, 2),
    invoice_amt_paid NUMERIC(31, 2),
    due_date DATETIME,
    inv_closed_date DATETIME,
    mail_return_date DATETIME,
    vb_inv_comment STRING,
    excused_by STRING,
    date_excused DATETIME,
    excused_reason STRING,
    excused_comment STRING,
    remailed STRING,
    date_created DATETIME,
    date_modified DATETIME,
    modified_by STRING,
    created_by STRING,
    past_due_late_fee_amount NUMERIC(31, 2),
    past_due_mail_fee_amount NUMERIC(31, 2),
    det_link_id NUMERIC(29),
    waived_late_fee_by STRING,
    waived_late_fee_date DATETIME,
    vbb_ln_batch_id NUMERIC(29),
    orig_due_date DATETIME,
    conversion_date DATETIME,
    det_link_id2 NUMERIC(29),
    last_update_date DATETIME,
    last_update_type STRING
)
cluster by vbi_invoice_id,vbi_account_id
;