-- Translation time: 2024-06-04T08:04:57.852399Z
-- Translation job ID: d189ef38-1420-4658-96a7-29624b482bd7
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_VPS/Tables/VP_OWNER_LANE_VIOLATIONS_CT_UPD.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_VPS.Vp_Owner_Lane_Violations_Ct_Upd
(
  lane_viol_id NUMERIC(29) NOT NULL,
  lane_viol_status STRING NOT NULL,
  lc_plaza_nbr STRING,
  lc_lane_nbr STRING,
  viol_date DATETIME NOT NULL,
  time_nbr NUMERIC(29) NOT NULL,
  sequence_nbr NUMERIC(29),
  lane_mode NUMERIC(29),
  employee_id NUMERIC(29),
  vehicle_class NUMERIC(29) NOT NULL,
  axle_count NUMERIC(29),
  violation_code NUMERIC(29),
  unusual_code NUMERIC(29),
  toll_due NUMERIC(31, 2),
  toll_paid NUMERIC(31, 2),
  agency_id NUMERIC(29),
  tag_id STRING,
  tag_status NUMERIC(29),
  vehicle_speed NUMERIC(29),
  consec_prev_viol NUMERIC(29),
  consec_follow_viol NUMERIC(29),
  poss_false_trigger STRING,
  device_status NUMERIC(29),
  fail_reason NUMERIC(29),
  lic_plate_nbr STRING,
  ocr_nbr_confid NUMERIC(29),
  lic_plate_state STRING,
  ocr_state_confid NUMERIC(29),
  image_name STRING,
  roi_image_name STRING,
  image_loc STRING,
  image_archive_loc STRING,
  ocr_confid_cutoff NUMERIC(29),
  state_confid_cutoff NUMERIC(29),
  reviewed_by STRING,
  pre_audit_result STRING NOT NULL,
  audit_result STRING,
  created_date DATETIME NOT NULL,
  modified_date DATETIME,
  lane_abbrev STRING NOT NULL,
  ves_name STRING NOT NULL,
  sequence_nbr1 NUMERIC(29),
  lane_controller_type STRING,
  review_status STRING NOT NULL,
  viol_reject_type STRING NOT NULL,
  review_date DATETIME,
  status_date DATETIME,
  viol_created STRING NOT NULL,
  review_user_id NUMERIC(29),
  lc_facility_code STRING,
  plaza_code STRING,
  lane_code STRING,
  lic_plate_nbr_2 STRING,
  host_transaction_id NUMERIC(29),
  lane_id NUMERIC(29) NOT NULL,
  ocr_plate_nbr STRING,
  ocr_plate_state STRING,
  dac_ocr_modified_date DATETIME,
  dac_ocr_plate_confid FLOAT64,
  dac_ocr_plate_nbr STRING,
  dac_ocr_plate_state STRING,
  source_server STRING,
  camera_lic_plate_nbr STRING,
  camera_lic_plate_state STRING,
  camera_lic_plate_confid NUMERIC(29),
  transaction_file_detail_id NUMERIC(29),
  subscriber_id STRING,
  insert_datetime DATETIME NOT NULL
)
;
