CREATE TABLE IF NOT EXISTS LND_LG_VPS.Vp_Owner_Vb_Statement_Invoices_Ct_Ins (
    vbsi_statement_id NUMERIC(29) NOT NULL,
    vbi_invoice_id NUMERIC(29) NOT NULL,
    vbi_invoice_status STRING,
    vbi_invoice_status_desc STRING,
    viol_invoice_id NUMERIC(29) NOT NULL,
    viol_invoice_status STRING,
    viol_invoice_status_desc STRING,
    vbsi_ca_invoice_status STRING,
    vbsi_invoice_notice_type STRING,
    vbsi_initial_invoice_date DATETIME,
    vbsi_vbi_invoice_amount NUMERIC(31, 2),
    vbsi_vbi_toll_due NUMERIC(31, 2),
    vbsi_vbi_late_fee_amount NUMERIC(31, 2),
    vbsi_vbi_invoice_disc NUMERIC(31, 2),
    vbsi_vbi_invoice_paid NUMERIC(31, 2),
    vbsi_invoice_amount NUMERIC(31, 2),
    vbsi_invoice_disc NUMERIC(31, 2),
    vbsi_invoice_paid NUMERIC(31, 2),
    vbsi_admin_fee NUMERIC(31, 2),
    vbsi_admin_fee_second_notice NUMERIC(31, 2),
    vbsi_ntta_tolls STRING,
    vbsi_highway_tolls STRING,
    vbsi_citations STRING,
    paid_indicator STRING,
    vbsi_prior_admin_fee STRING,
    vbsi_prior_admin_fee_2 STRING,
    insert_datetime DATETIME NOT NULL
);