-- Translation time: 2024-06-04T07:57:18.317878Z
-- Translation job ID: b2abff43-eccf-406a-aa5d-053048797d89
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_HOST/Tables/HAS_OWNER_HA_SHIFT_DETAILS.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_HOST.Has_Owner_Ha_Shift_Details
(
  summary_type STRING,
  start_time DATETIME,
  end_time DATETIME,
  summ_time DATETIME,
  shift_end_time DATETIME,
  shift_start_time DATETIME,
  shift_type STRING,
  bus_day DATETIME,
  pmt_type STRING,
  class STRING,
  axle_ind_cnt INT64,
  axle_exp_cnt INT64,
  axle_act_cnt INT64,
  veh_tot_cnt INT64,
  veh_avi_cnt INT64,
  veh_avi_nr_cnt INT64,
  veh_avi_inv_cnt INT64,
  veh_acm_cnt INT64,
  veh_cash_att_cnt INT64,
  veh_no_fund_cnt INT64,
  veh_at_nr_cnt INT64,
  veh_part_vio_pmt_cnt INT64,
  veh_avi_vio_cnt INT64,
  veh_vio_cnt INT64,
  rev_tot_earned NUMERIC(29),
  rev_tot_exp NUMERIC(29),
  rev_tot_act NUMERIC(29),
  rev_avi NUMERIC(29),
  rev_avi_nr NUMERIC(29),
  rev_avi_inv NUMERIC(29),
  rev_acm NUMERIC(29),
  rev_cash_att NUMERIC(29),
  rev_no_fund NUMERIC(29),
  rev_att_nr NUMERIC(29),
  rev_vio_cnt NUMERIC(29),
  rev_avi_vio NUMERIC(29),
  rev_cash_vio NUMERIC(29),
  rev_part_vio_pmt NUMERIC(29),
  ln_mode STRING,
  misclass_ct NUMERIC(29),
  shift_id INT64,
  vplt_id INT64,
  att_empl_id INT64,
  opnm_id INT64,
  avg_hshks INT64,
  exit_loop INT64,
  mid_loop INT64,
  ent_loop INT64,
  fwd_axles INT64,
  rev_axles INT64,
  hsd_id BIGNUMERIC(48, 10),
  lane_lane_id NUMERIC(29),
  pmty_id INT64,
  vcly_id INT64,
  gate_override_cnt INT64,
  det_link_id NUMERIC(29),
  last_update_type STRING,
  last_update_date DATETIME
)
;
