-- Translation time: 2024-06-04T07:57:18.317878Z
-- Translation job ID: b2abff43-eccf-406a-aa5d-053048797d89
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_HOST/Tables/TSA_OWNER_TRANSACTION_FILE_DETAILS.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_HOST.Tsa_Owner_Transaction_File_Details
(
  transaction_file_detail_id NUMERIC(29),
  subs_trans_type_code STRING,
  transaction_file_header_id NUMERIC(29),
  transaction_sequence INT64,
  record_type STRING,
  subscriber_unique_id NUMERIC(29),
  revenue_date DATETIME,
  received_date DATETIME,
  resubmittal_reason STRING,
  resubmittal_count STRING,
  transaction_status STRING,
  authority_id STRING,
  location_type STRING,
  facility STRING,
  subscriber_id STRING,
  entry_plaza STRING,
  entry_lane STRING,
  entry_lane_mode STRING,
  entry_transaction_date STRING,
  entry_transaction_time STRING,
  entry_transponder_id STRING,
  entry_transponder_status STRING,
  entry_tvl_file_name STRING,
  entry_lvl_file_name STRING,
  entry_vehicle_class STRING,
  entry_axles_expected STRING,
  entry_axles_counted STRING,
  entry_speed STRING,
  entry_hov_designation STRING,
  exit_plaza STRING,
  exit_lane STRING,
  exit_lane_mode STRING,
  exit_transaction_date DATETIME,
  exit_transaction_time STRING,
  exit_transponder_id STRING,
  exit_transponder_status STRING,
  exit_tvl_file_name STRING,
  exit_lvl_file_name STRING,
  exit_vehicle_class STRING,
  exit_axles_expected STRING,
  exit_axles_counted STRING,
  exit_speed STRING,
  exit_hov_designation STRING,
  collector_id STRING,
  vault_id STRING,
  toll_determination_class STRING,
  transponder_toll_amt STRING,
  transponder_discount_type STRING,
  disc_transponder_toll_amt STRING,
  video_toll_amt_wo_prem STRING,
  video_toll_amt_w_prem STRING,
  video_discount_type STRING,
  disc_video_toll_amt_wo_prem STRING,
  disc_video_toll_amt_w_prem STRING,
  cash_toll_amount STRING,
  cash_discount_type STRING,
  disc_cash_toll_amount STRING,
  unusual_occurrence_code STRING,
  number_of_images STRING,
  amount_paid STRING,
  image_request_send_date DATETIME,
  image_response_received_date DATETIME,
  image_request_status_code STRING,
  created_by STRING,
  date_created DATETIME,
  modified_by STRING,
  date_modified DATETIME,
  additional_comments STRING,
  subscriber_list_id INT64,
  processed_yn STRING,
  locked_timestamp DATETIME,
  exit_tag_id STRING,
  last_update_type STRING,
  last_update_date DATETIME
)
;
