CREATE TABLE [Ref].[Ban] (
    [ViolatorID] bigint NULL, 
    [VidSeq] int NULL, 
    [HvFlag] smallint NULL, 
    [INDICATOR] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [DayID] int NULL, 
    [DayDate] date NULL, 
    [DayDesc] varchar(18) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ViolatorStatusLetterDeterminationLookupId] int NULL, 
    [ViolatorStatusLetterDetermination] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [DayID0] int NULL, 
    [DayDate0] date NULL, 
    [DayDesc0] varchar(18) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ViolatorStatusLetterVrbLookupID] int NULL, 
    [ViolatorStatusLetterVrbLookupDesc] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ViolatorStatusLetterBanLookupId] int NULL, 
    [ViolatorStatusLetterBan] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [DayID1] int NULL, 
    [DayDate1] date NULL, 
    [DayDesc1] varchar(18) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [DayID2] int NULL, 
    [DayDate2] date NULL, 
    [DayDesc2] varchar(18) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [LicPlateStateLookupID] int NULL, 
    [LicPlateStateName] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [LicPlateState] varchar(6) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Cal_MonthID] int NOT NULL, 
    [MonthDesc] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [DayID3] int NULL, 
    [DayDate3] date NULL, 
    [DayDesc3] varchar(18) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ViolatorID0] bigint NULL, 
    [Ban] varchar(6) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [RegistrationCountyLookupID] int NULL, 
    [RegistrationCounty] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL
)
WITH (HEAP, DISTRIBUTION = HASH([ViolatorID]));
