CREATE TABLE [Temp].[Dim_OperationsMapping_NEW_20240109] (
    [TripIdentMethod] varchar(9) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripWith] char(1) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TransactionPostingType] varchar(15) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripStageCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripStatusCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ReasonCode] varchar(255) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [CitationStageCode] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripPaymentStatusDesc] varchar(100) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [SourceName] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [OperationsAgency] varchar(20) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [BadAddressFlag] smallint NOT NULL, 
    [NonRevenueFlag] smallint NOT NULL, 
    [BusinessRuleMatchedFlag] smallint NOT NULL, 
    [TripIdentMethodID] smallint NOT NULL, 
    [TripIdentMethodCode] varchar(7) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [TransactionPostingTypeID] int NULL, 
    [TransactionPostingTypeDesc] varchar(500) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripStageID] bigint NULL, 
    [TripStageDesc] varchar(250) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripStatusID] bigint NULL, 
    [TripStatusDesc] varchar(250) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ReasonCodeID] bigint NULL, 
    [CitationStageID] int NULL, 
    [CitationStageDesc] varchar(256) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripPaymentStatusID] int NULL, 
    [TripPaymentStatusCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [EDW_UpdateDate] datetime2(3) NULL
)
WITH (HEAP, DISTRIBUTION = ROUND_ROBIN);
