CREATE TABLE [Temp].[Fact_UnifiedTransaction_SummarySnapshot_20240110] (
    [SnapshotMonthID] int NULL, 
    [AsOfDayID] int NULL, 
    [RowSeq] int NULL, 
    [TripMonthID] int NULL, 
    [FacilityID] int NULL, 
    [FacilityCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [OperationsAgency] varchar(20) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [OperationsMappingID] int NULL, 
    [Mapping] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [MappingDetailed] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [PursUnpursStatus] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripWith] char(1) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TripIdentMethodID] int NULL, 
    [RecordTypeID] int NOT NULL, 
    [TransactionPostingTypeID] int NULL, 
    [TripStageID] bigint NULL, 
    [TripStatusID] bigint NULL, 
    [ReasonCodeID] bigint NULL, 
    [CitationStageID] int NULL, 
    [TripPaymentStatusID] bigint NULL, 
    [SourceName] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [BadAddressFlag] smallint NULL, 
    [NonRevenueFlag] smallint NULL, 
    [BusinessRuleMatchedFlag] smallint NULL, 
    [ManuallyReviewedFlag] smallint NULL, 
    [OOSPlateFlag] smallint NULL, 
    [VTollFlag] smallint NULL, 
    [ClassAdjustmentFlag] smallint NULL, 
    [FirstPaidMonthID] int NOT NULL, 
    [LastPaidMonthID] int NOT NULL, 
    [Rpt_PaidvsAEA] varchar(4) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_PurUnP] varchar(20) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_LPState] varchar(3) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_InvUnInv] varchar(7) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_VToll] varchar(15) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_IRStatus] varchar(11) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_ProcessStatus] varchar(22) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_PaidStatus] varchar(18) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Rpt_IRRejectStatus] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TxnCount] bigint NULL, 
    [ExpectedAmount] decimal(19, 2) NULL, 
    [AdjustedExpectedAmount] decimal(19, 2) NULL, 
    [CalcAdjustedAmount] decimal(19, 2) NULL, 
    [TripWithAdjustedAmount] decimal(19, 2) NULL, 
    [TollAmount] decimal(19, 2) NULL, 
    [ActualPaidAmount] decimal(19, 2) NULL, 
    [OutstandingAmount] decimal(19, 2) NULL, 
    [LND_UpdateDate] datetime2(3) NULL, 
    [EDW_UpdateDate] datetime2(7) NULL, 
    [BackupDate] datetime2(3) NULL
)
WITH (CLUSTERED INDEX ( [SnapshotMonthID] ASC ), DISTRIBUTION = HASH([OperationsMappingID]));
