CREATE TABLE [Temp].[Stage_UnifiedTransaction_20240107] (
    [TPTripID] bigint NOT NULL, 
    [CustTripID] bigint NULL, 
    [CitationID] bigint NULL, 
    [TripDate] datetime2(3) NULL, 
    [TripDayID] int NOT NULL, 
    [LaneID] int NULL, 
    [CustomerID] bigint NOT NULL, 
    [OperationsMappingID] int NOT NULL, 
    [TripIdentMethod] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [LaneTripIdentMethod] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [RecordType] varchar(5) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [TripWith] char(1) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TransactionPostingType] varchar(25) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [TripStageID] int NOT NULL, 
    [TripStageCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [TripStatusID] int NOT NULL, 
    [TripStatusCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [ReasonCode] varchar(255) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [CitationStageCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [TripPaymentStatusID] bigint NOT NULL, 
    [TripPaymentStatusDesc] varchar(100) COLLATE Latin1_General_100_CI_AS_KS_WS NOT NULL, 
    [SourceName] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [OperationsAgency] varchar(20) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [FacilityCode] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [VehicleID] bigint NOT NULL, 
    [VehicleNumber] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [VehicleState] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TagRefID] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [TagAgency] varchar(6) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [VehicleClass] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [RevenueVehicleClass] int NULL, 
    [SourceOfEntry] tinyint NULL, 
    [SourceTripID] bigint NULL, 
    [Disposition] varchar(2) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [IPSTransactionID] bigint NULL, 
    [VESSerialNumber] bigint NULL, 
    [ShowBadAddressFlag] bit NULL, 
    [BadAddressFlag] smallint NOT NULL, 
    [NonRevenueFlag] smallint NOT NULL, 
    [BusinessRuleMatchedFlag] smallint NOT NULL, 
    [ManuallyReviewedFlag] smallint NOT NULL, 
    [OOSPlateFlag] smallint NOT NULL, 
    [VTollFlag] smallint NULL, 
    [ClassAdjustmentFlag] smallint NOT NULL, 
    [Rpt_PaidvsAEA] varchar(4) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [ExpectedAmount] decimal(19, 2) NULL, 
    [AdjustedExpectedAmount] decimal(19, 2) NULL, 
    [CalcAdjustedAmount] decimal(19, 2) NOT NULL, 
    [TripWithAdjustedAmount] decimal(19, 2) NULL, 
    [TollAmount] decimal(19, 2) NULL, 
    [ActualPaidAmount] decimal(19, 2) NOT NULL, 
    [OutStandingAmount] decimal(19, 2) NOT NULL, 
    [FirstPaidDate] datetime2(3) NULL, 
    [LastPaidDate] datetime2(3) NULL, 
    [TxnAgencyID] bigint NULL, 
    [AccountAgencyID] bigint NULL, 
    [TP_PostedDate] datetime2(3) NULL, 
    [CustTrip_PostedDate] datetime2(3) NULL, 
    [ViolatedTrip_PostedDate] datetime2(3) NULL, 
    [UT_AdjustedExpectedAmount] decimal(19, 2) NULL, 
    [UT_ActualPaidAmount] decimal(19, 2) NULL, 
    [ExpectedBase] decimal(19, 2) NULL, 
    [ExpectedPremium] decimal(19, 2) NULL, 
    [AVITollAmount] decimal(19, 2) NULL, 
    [PBMTollAmount] decimal(19, 2) NULL, 
    [OriginalAVITollAmount] decimal(19, 2) NULL, 
    [OriginalPBMTollAmount] decimal(19, 2) NULL, 
    [TP_ReceivedTollAmount] decimal(19, 2) NULL, 
    [NRaw_FareAmount] decimal(19, 2) NULL, 
    [NRaw_VehicleClass_TagFare] decimal(19, 2) NULL, 
    [NRaw_VehicleClass_PlateFare] decimal(19, 2) NULL, 
    [TP_VehicleClass_TagFare] decimal(19, 2) NULL, 
    [TP_VehicleClass_PlateFare] decimal(19, 2) NULL, 
    [TSA_ReceivedTollAmount] decimal(19, 2) NULL, 
    [ViolatedTripPayment_TotalTxnAmount] decimal(19, 2) NULL, 
    [ViolatedTripPayment_AdjustedAmount] decimal(19, 2) NULL, 
    [ViolatedTripPayment_ActualPaidAmount] decimal(19, 2) NULL, 
    [UT_TollAmount] decimal(19, 2) NULL, 
    [TP_TollAmount] decimal(19, 2) NULL, 
    [CustTrip_TollAmount] decimal(19, 2) NULL, 
    [ViolatedTrip_TollAmount] decimal(19, 2) NULL, 
    [TP_OutStandingAmount] decimal(19, 2) NULL, 
    [CustTrip_OutStandingAmount] decimal(19, 2) NULL, 
    [ViolatedTrip_OutStandingAmount] decimal(19, 2) NULL, 
    [TP_TripStatusID] int NULL, 
    [CustTrip_TripStatusID] int NULL, 
    [ViolatedTrip_TripStatusID] int NULL, 
    [TP_TripStageID] int NULL, 
    [CustTrip_TripStageID] int NULL, 
    [ViolatedTrip_TripStageID] int NULL, 
    [TP_PaymentStatusID] bigint NULL, 
    [CustTrip_PaymentStatusID] bigint NULL, 
    [ViolatedTrip_PaymentStatusID] bigint NULL, 
    [TTT_RecordType] varchar(5) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [LND_UpdateDate] datetime2(3) NULL, 
    [EDW_UpdateDate] datetime2(3) NULL
)
WITH (CLUSTERED INDEX ( [TPTripID] ASC ), DISTRIBUTION = HASH([TPTripID]));
