CREATE TABLE [Temp].[Fact_UnifiedTransaction_Summary_20240107] (
    [TripDayID] int NOT NULL, 
    [LaneID] int NULL, 
    [OperationsMappingID] int NULL, 
    [TripWith] char(1) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [SourceofEntry] tinyint NULL, 
    [TripIdentMethodID] int NULL, 
    [LaneTripIdentMethodID] smallint NOT NULL, 
    [RecordTypeID] smallint NOT NULL, 
    [TransactionPostingTypeID] int NULL, 
    [TripStageID] bigint NULL, 
    [TripStatusID] bigint NULL, 
    [ReasonCodeID] bigint NULL, 
    [CitationStageID] int NULL, 
    [TripPaymentStatusID] bigint NULL, 
    [VehicleClassID] int NULL, 
    [BadAddressFlag] smallint NULL, 
    [NonRevenueFlag] smallint NULL, 
    [BusinessRuleMatchedFlag] smallint NULL, 
    [ManuallyReviewedFlag] smallint NOT NULL, 
    [OOSPlateFlag] smallint NOT NULL, 
    [VTollFlag] smallint NULL, 
    [ClassAdjustmentFlag] smallint NOT NULL, 
    [Rpt_PaidvsAEA] varchar(4) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [FirstPaidDate] date NULL, 
    [LastPaidDate] date NULL, 
    [TxnCount] bigint NULL, 
    [ExpectedAmount] decimal(19, 2) NULL, 
    [AdjustedExpectedAmount] decimal(19, 2) NULL, 
    [CalcAdjustedAmount] decimal(19, 2) NULL, 
    [TripWithAdjustedAmount] decimal(19, 2) NULL, 
    [TollAmount] decimal(19, 2) NULL, 
    [ActualPaidAmount] decimal(19, 2) NULL, 
    [OutstandingAmount] decimal(19, 2) NULL, 
    [LND_UpdateDate] datetime2(3) NULL, 
    [EDW_UpdateDate] datetime2(3) NULL
)
WITH (CLUSTERED COLUMNSTORE INDEX, DISTRIBUTION = HASH([TripDayID]));
