
CREATE TABLE IF NOT EXISTS EDW_TER.Dim_Violator
(
  violatorid INT64,
  vidseq INT64,
  current_ind INT64,
  hv_non_hv_ind INT64,
  licplatenbr STRING,
  licplatestatelookupid INT64,
  licplatestate STRING,
  license_plate_id INT64,
  vehicle_id INT64,
  docnum STRING,
  vin STRING,
  primaryviolatorfname STRING,
  primaryviolatorlname STRING,
  secondaryviolatorfname STRING,
  secondaryviolatorlname STRING,
  driverslicense STRING,
  driverslicensestatelookupid INT64,
  secondarydriverslicense STRING,
  secondarydriverslicensestatelookupid INT64,
  earliesthvtrandate DATE,
  latesthvtrandate DATE,
  admincountylookupid INT64,
  registrationcountylookupid INT64,
  registrationdatenextmonth INT64,
  registrationdatenextyear INT64,
  violatoragencylookupid INT64,
  violatoraddresssourcelookupid INT64,
  violatoraddressstatuslookupid INT64,
  violatoraddressactiveflag INT64,
  violatoraddressconfirmedflag INT64,
  violatoraddress1 STRING,
  violatoraddress2 STRING,
  violatoraddresscity STRING,
  violatoraddressstatelookupid INT64,
  violatoraddresszipcode STRING,
  violatoraddressplus4 STRING,
  violatoraddresscreatedby STRING,
  violatoraddressupdatedby STRING,
  violatorstatusid INT64,
  violatorstatuslookupid INT64,
  violatorstatustermlookupid INT64,
  violatorstatuseligrmdylookupid INT64,
  violatorstatusletterdeterminationlookupid INT64,
  violatorstatusletterbanlookupid INT64,
  violatorstatuslettertermlookupid INT64,
  violatorstatusletterban2ndlookupid INT64,
  violatorstatuslettervrblookupid INT64,
  banbyprocessserver INT64,
  banbydps INT64,
  banbyusmail1stban INT64,
  acct_id INT64,
  acct_status_code STRING,
  tag_date_created DATE,
  banflag INT64,
  bancitewarnflag INT64,
  banimpoundflag INT64,
  bankruptcyind INT64,
  banletterflag INT64,
  defaultind INT64,
  determinationletterflag INT64,
  eligrmdyflag INT64,
  has_toll_tag_account INT64,
  hvactive INT64,
  hvexemptflag INT64,
  hvflag INT64,
  hvremoved INT64,
  termflag INT64,
  termletterflag INT64,
  vrbacknowledged INT64,
  vrbflag INT64,
  vrbremoved INT64,
  vrbremovalqueued INT64,
  ban2ndletterflag INT64,
  vrbletterflag INT64,
  adminfees NUMERIC(33, 4),
  balance_amount NUMERIC(33, 4),
  balancedue NUMERIC(33, 4),
  bancitewarncount INT64,
  citationfees NUMERIC(33, 4),
  collectableamount NUMERIC(33, 4),
  collections NUMERIC(33, 4),
  downpayment NUMERIC(33, 4),
  excusedamount NUMERIC(33, 4),
  hvqamountdue NUMERIC(33, 4),
  hvqtollsdue NUMERIC(33, 4),
  hvqtransactions INT64,
  hvqfeesdue NUMERIC(33, 4),
  monthlypaymentamount NUMERIC(33, 4),
  paidinfull INT64,
  pmt_type_code STRING,
  rebill_amt NUMERIC(31, 2),
  settlementamount NUMERIC(33, 4),
  tolltransactioncount INT64,
  totalamountdue NUMERIC(33, 4),
  totalamountdueinitial NUMERIC(33, 4),
  totalcitationcount INT64,
  totalfeesdue NUMERIC(33, 4),
  totaltollsdue NUMERIC(33, 4),
  totaltransactionscount INT64,
  totaltransactionsinitial INT64,
  bandpscount INT64,
  banpcpcount INT64,
  banwarncount INT64,
  bancitationcount INT64,
  banimpoundcount INT64,
  bannoactioncount INT64,
  banfennellcount INT64,
  violatoraddresscreatedate DATETIME,
  violatoraddressupdatedate DATETIME,
  bal_last_updated DATETIME,
  bancitewarndate DATE,
  bandate DATE,
  banimpounddate DATE,
  banletterdate DATE,
  banstartdate DATE,
  determinationletterdate DATE,
  eligrmdydate DATE,
  hvdate DATE,
  hvexemptdate DATE,
  rebill_date DATETIME,
  termdate DATE,
  termletterdate DATE,
  vrbdate DATE,
  ban2ndletterdate DATETIME,
  vrbletterdate DATETIME,
  phonenbr STRING,
  workphonenbr STRING,
  otherphonenbr STRING,
  emailaddress STRING,
  tolltagnbr STRING
)
cluster by violatorid,vidseq
;
