
CREATE TABLE IF NOT EXISTS EDW_TER.Violator_Bankruptcy
(
  violatorid INT64 NOT NULL,
  vidseq INT64 NOT NULL,
  bankruptcyinstancenbr INT64 NOT NULL,
  lastname STRING,
  firstname STRING,
  lastname2 STRING,
  firstname2 STRING,
  licenseplate STRING,
  casenumber STRING,
  datenotified DATE,
  filingdate DATE,
  conversiondate DATE,
  excusedamount NUMERIC(33, 4),
  collectableamount NUMERIC(33, 4),
  phonenumber STRING,
  dischargedismissedid INT64,
  discharge_dismissed_date DATE,
  assets INT64 NOT NULL,
  collectionaccounts INT64 NOT NULL,
  lawfirm STRING,
  attorneyname STRING,
  claimfilled INT64 NOT NULL,
  comments STRING,
  filingstatusid INT64 NOT NULL,
  insertdate DATETIME NOT NULL,
  insertbyuser STRING NOT NULL,
  lastupdatedate DATETIME,
  lastupdatebyuser STRING,
  insert_date DATETIME NOT NULL,
  last_update_date DATETIME NOT NULL
)
;
