
CREATE TABLE IF NOT EXISTS EDW_TER.Ter_Letter_Alerts_Determination
(
  alertsrunid INT64 NOT NULL,
  determinationletterdueweek DATE,
  sentstatus STRING,
  alertlevel STRING NOT NULL,
  determinationletteranalysis STRING,
  paymentplantiming STRING,
  paymenttiming STRING,
  bankruptcytiming STRING,
  violatorid INT64 NOT NULL,
  vidseq INT64 NOT NULL,
  hvdate DATETIME NOT NULL,
  violatorcreateddate DATETIME NOT NULL,
  determinationletterduemonday DATETIME,
  determinationletterdate DATETIME,
  determinationletterqueueddate DATETIME,
  determinationletterqueuecanceldate DATETIME,
  determinationlettersenddate DATETIME,
  questmarkdetletterackdate DATETIME,
  usercanceldate DATETIME,
  determinationletterstatus STRING,
  violatorstatus STRING,
  violatorstatuseligrmdy STRING,
  applypaymentplandate DATETIME,
  activeagreementdate DATETIME,
  defaulteddate DATETIME,
  rite_paidinfulldate DATETIME,
  pp_paidinfulldate DATETIME,
  termdate DATETIME,
  bankruptcydate DATETIME,
  bankruptcydismisseddate DATETIME,
  adminhearingdate DATETIME,
  hvflag INT64 NOT NULL,
  eligrmdyflag INT64 NOT NULL,
  determinationletterflag INT64 NOT NULL,
  nonhvpaymentplanid INT64,
  paymentplanid INT64,
  planstartdate DATETIME,
  planenddate DATETIME,
  paymentplanstatus STRING,
  paymentplancount INT64,
  totalnoofmonths INT64,
  generationdate DATETIME NOT NULL
)
;
