
CREATE TABLE IF NOT EXISTS EDW_TER.Violator_PaymentAgreement_Stage
(
  violatorid FLOAT64 NOT NULL,
  vidseq INT64 NOT NULL,
  instancenbr INT64 NOT NULL,
  lastname STRING,
  firstname STRING,
  phonenumber STRING,
  licenseplate STRING,
  state STRING NOT NULL,
  agentid INT64 NOT NULL,
  paymentagreement_source STRING NOT NULL,
  settlementamount NUMERIC(33, 4),
  downpayment NUMERIC(33, 4),
  duedate DATETIME NOT NULL,
  agreementtype STRING NOT NULL,
  todaysdate DATETIME NOT NULL,
  collections NUMERIC(33, 4),
  remainingbalancedue STRING,
  paymentplanduedate DATETIME NOT NULL,
  checknumber STRING,
  paidinfull INT64 NOT NULL,
  defaultind INT64 NOT NULL,
  spanishonly INT64 NOT NULL,
  amnestyaccount INT64 NOT NULL,
  tolltag_acct_id NUMERIC(29),
  adminfees NUMERIC(33, 4),
  citationfees NUMERIC(33, 4),
  monthlypaymentamount NUMERIC(33, 4),
  defaultdate DATE NOT NULL,
  maintenanceagency STRING NOT NULL,
  violatorid2 INT64,
  violatorid3 INT64,
  violatorid4 INT64,
  balancedue NUMERIC(33, 4),
  ntta_collections NUMERIC(33, 4),
  enforcement_tool_code STRING,
  enforcement_tool_date DATE,
  contactsource STRING,
  paymentplanstatus STRING,
  insertdate DATETIME NOT NULL,
  insertbyuser STRING NOT NULL,
  lastupdatedate DATETIME,
  lastupdatebyuser STRING,
  last_update_type STRING NOT NULL,
  last_update_date DATETIME NOT NULL
)
cluster by vidseq
;
