CREATE TABLE IF NOT EXISTS EDW_TER.ViolatorStatus_Stage
(
  violatorstatusid INT64 NOT NULL,
  violatorid INT64 NOT NULL,
  vidseq INT64 NOT NULL,
  hvflag INT64 NOT NULL,
  hvdate DATETIME NOT NULL,
  violatorstatuslookupid INT64 NOT NULL,
  hvexemptflag INT64 NOT NULL,
  hvexemptdate DATETIME NOT NULL,
  violatorstatustermlookupid INT64 NOT NULL,
  termflag INT64 NOT NULL,
  termdate DATETIME NOT NULL,
  violatorstatuseligrmdylookupid INT64 NOT NULL,
  eligrmdyflag INT64 NOT NULL,
  eligrmdydate DATETIME NOT NULL,
  banflag INT64 NOT NULL,
  bandate DATETIME NOT NULL,
  banstartdate DATETIME NOT NULL,
  bancitewarnflag INT64 NOT NULL,
  bancitewarndate DATETIME NOT NULL,
  bancitewarncount INT64,
  banimpoundflag INT64 NOT NULL,
  banimpounddate DATETIME NOT NULL,
  vrbflag INT64 NOT NULL,
  vrbdate DATETIME NOT NULL,
  violatorstatusletterdeterminationlookupid INT64 NOT NULL,
  determinationletterflag INT64 NOT NULL,
  determinationletterdate DATETIME NOT NULL,
  violatorstatusletterbanlookupid INT64 NOT NULL,
  banletterflag INT64 NOT NULL,
  banletterdate DATETIME NOT NULL,
  violatorstatuslettertermlookupid INT64 NOT NULL,
  termletterflag INT64 NOT NULL,
  termletterdate DATETIME NOT NULL,
  hvqamountdue NUMERIC(33, 4),
  hvqtollsdue NUMERIC(33, 4),
  hvqtransactions INT64,
  hvqfeesdue NUMERIC(33, 4),
  totalamountdue NUMERIC(33, 4),
  totaltollsdue NUMERIC(33, 4),
  totalfeesdue NUMERIC(33, 4),
  totalcitationcount INT64,
  totaltransactionscount INT64,
  settlementamount NUMERIC(33, 4),
  downpayment NUMERIC(33, 4),
  collections NUMERIC(33, 4),
  paidinfull INT64,
  defaultind INT64,
  adminfees NUMERIC(33, 4),
  citationfees NUMERIC(33, 4),
  monthlypaymentamount NUMERIC(33, 4),
  balancedue NUMERIC(33, 4),
  excusedamount NUMERIC(33, 4),
  collectableamount NUMERIC(33, 4),
  bankruptcyind INT64,
  ban2ndletterdate DATETIME NOT NULL,
  ban2ndletterflag INT64 NOT NULL,
  violatorstatusletterban2ndlookupid INT64 NOT NULL,
  violatorstatuslettervrblookupid INT64 NOT NULL,
  vrbletterdate DATETIME NOT NULL,
  vrbletterflag INT64 NOT NULL,
  bandpscount INT64 NOT NULL,
  banpcpcount INT64 NOT NULL,
  banwarncount INT64 NOT NULL,
  bancitationcount INT64 NOT NULL,
  banimpoundcount INT64 NOT NULL,
  bannoactioncount INT64 NOT NULL,
  banfennellcount INT64 NOT NULL,
  violatorstatus_last_update_type STRING NOT NULL,
  violatoramountssummary_last_update_type STRING,
  violatorstatus_last_update_date DATETIME NOT NULL,
  violatoramountssummary_last_update_date DATETIME
)
cluster by violatorid,vidseq
;
