CREATE TABLE IF NOT EXISTS EDW_TER.Dto_Cal_Qtr
(
  cal_id INT64 NOT NULL,
  cal_qtr_bgn DATE NOT NULL,
  cal_qtr_end DATE NOT NULL,
  cal_qtr_ix INT64,
  cal_qtr_sea_bgn DATE,
  cal_qtr_yr_bgn DATE NOT NULL,
  cal_sea_bgn DATE,
  cal_sea_end DATE,
  cal_sea_ix INT64,
  cal_sea_yr_bgn DATE,
  cal_yr_bgn DATE NOT NULL,
  cal_yr_end DATE NOT NULL,
  cal_yr_ix INT64,
  cal_yr_leap INT64 NOT NULL,
  cal_qtrs_sea INT64,
  cal_qtr_sea INT64,
  cal_qtrs_yr INT64 NOT NULL,
  cal_qtr_yr INT64 NOT NULL,
  cal_seas_yr INT64,
  cal_sea_yr INT64,
  cal_qtr_sid STRING,
  cal_sea_sid STRING,
  cal_yr_sid STRING,
  cal_qtr_sea_sid STRING,
  cal_qtr_yr_sid STRING,
  cal_sea_yr_sid STRING,
  cal_qtr_desc_1 STRING,
  cal_sea_desc_1 STRING,
  cal_yr_desc_1 STRING,
  cal_qtr_sea_desc_1 STRING,
  cal_qtr_yr_desc_1 STRING,
  cal_sea_yr_desc_1 STRING,
  cal_qtr_desc_2 STRING,
  cal_sea_desc_2 STRING,
  cal_yr_desc_2 STRING,
  cal_qtr_sea_desc_2 STRING,
  cal_qtr_yr_desc_2 STRING,
  cal_sea_yr_desc_2 STRING,
  etl_sid INT64 NOT NULL,
  etl_chg STRING NOT NULL,
  etl_day DATETIME NOT NULL
)
;
