-- Translation time: 2024-06-04T08:01:15.437249Z
-- Translation job ID: a14a1a7f-7d63-47c9-8296-0b7483d5c271
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_IOP/Tables/IOP_OWNER_IOP_TXNS.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_IOP.Iop_Owner_Iop_Txns
(
  iop_txn_id NUMERIC(29),
  tag_id STRING,
  tag_identifier STRING,
  txn_type STRING,
  entry_txn_date DATETIME,
  entry_lane_id NUMERIC(29),
  entry_loc STRING,
  entry_tvl_tag_status STRING,
  exit_txn_date DATETIME,
  exit_lane_id NUMERIC(29),
  exit_loc STRING,
  exit_tvl_tag_status STRING,
  earned_class INT64,
  earned_revenue NUMERIC(31, 2),
  posted_date DATETIME,
  local_posted_date DATETIME,
  disposition STRING,
  reason_code STRING,
  posted_class INT64,
  posted_revenue NUMERIC(31, 2),
  txn_status STRING,
  is_guaranteed STRING,
  source_agcy_id NUMERIC(29),
  agency_code STRING,
  hia_agency_id NUMERIC(29),
  source_code STRING,
  source_txn_id NUMERIC(29),
  peer_iop_txn_id NUMERIC(29),
  surcharge_fee_type STRING,
  surcharge_fee NUMERIC(31, 2),
  lic_plate_state STRING,
  lic_plate_nbr STRING,
  resubmit_count NUMERIC(29),
  repost_count INT64,
  created_by STRING,
  date_created DATETIME,
  modified_by STRING,
  date_modified DATETIME,
  iop_disposition STRING,
  entry_revenue_type INT64,
  exit_revenue_type INT64,
  entry_tvl_batch_id NUMERIC(29),
  exit_tvl_batch_id NUMERIC(29),
  proc_fee_flat NUMERIC(34, 5),
  proc_fee_flat_type STRING,
  proc_fee_pct NUMERIC(34, 5),
  proc_fee_pct_type STRING,
  attribute_1 STRING,
  attribute_2 STRING,
  attribute_3 STRING,
  attribute_4 STRING,
  attribute_5 STRING,
  attribute_6 STRING,
  attribute_7 STRING,
  attribute_8 STRING,
  attribute_9 STRING,
  attribute_10 STRING,
  rev_changed STRING,
  gl_link_id NUMERIC(29),
  last_update_type STRING,
  last_update_date DATETIME
)
;
