-- Translation time: 2024-06-04T08:01:15.437249Z
-- Translation job ID: a14a1a7f-7d63-47c9-8296-0b7483d5c271
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_IOP/Tables/IOP_OWNER_HUB_IOP_TXNS_CT_DEL.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_IOP.Iop_Owner_Hub_Iop_Txns_Ct_Del
(
  hub_iop_txn_id NUMERIC(29) NOT NULL,
  record_type STRING NOT NULL,
  txn_reference_id NUMERIC(29),
  host_txn_id NUMERIC(29),
  exit_txn_date DATETIME NOT NULL,
  exit_lane NUMERIC(29) NOT NULL,
  entry_txn_date DATETIME,
  entry_lane NUMERIC(29),
  tag_agency_id STRING,
  tag_serial_number STRING,
  tag_status STRING,
  occupancy_indicator STRING,
  vehicle_class INT64 NOT NULL,
  earned_revenue NUMERIC(31, 2) NOT NULL,
  discount_plan STRING,
  lic_plate_country STRING,
  lic_plate_state STRING,
  lic_plate_number STRING,
  lic_plate_type STRING,
  vehicle_class_adj_flag STRING,
  sys_matched_flag STRING,
  txn_status STRING NOT NULL,
  is_guaranteed STRING,
  source_code STRING,
  disposition STRING,
  reason_code STRING,
  system_error STRING,
  adj_failed_disp_reason_code STRING,
  acct_id NUMERIC(29),
  acct_bal_before_posting NUMERIC(31, 2),
  acct_bal_after_posting NUMERIC(31, 2),
  tvl_tag_status STRING,
  adjustment_date DATETIME,
  adjustment_reason STRING,
  other_adjustment_desc STRING,
  adjustment_count INT64,
  resubmit_reason STRING,
  resubmit_count INT64,
  home_txn_reference_id NUMERIC(29),
  iop_away_agency_id STRING,
  iop_home_agency_id STRING,
  iop_disposition STRING,
  posted_discount_plan STRING,
  posted_revenue NUMERIC(31, 2),
  posted_date DATETIME,
  local_posted_date DATETIME,
  proc_fee_flat NUMERIC(34, 5),
  proc_fee_pct NUMERIC(34, 5),
  adjustment_identifier STRING,
  original_hub_iop_txn_id NUMERIC(29),
  attribute_1 STRING,
  attribute_2 STRING,
  attribute_3 STRING,
  attribute_4 STRING,
  attribute_5 STRING,
  attribute_6 STRING,
  attribute_7 STRING,
  attribute_8 STRING,
  attribute_9 STRING,
  attribute_10 STRING,
  created_by STRING NOT NULL,
  date_created DATETIME NOT NULL,
  modified_by STRING NOT NULL,
  date_modified DATETIME NOT NULL,
  insert_datetime DATETIME NOT NULL
)
;
