-- Translation time: 2024-06-04T08:01:15.437249Z
-- Translation job ID: a14a1a7f-7d63-47c9-8296-0b7483d5c271
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_IOP/Tables/IOP_OWNER_HUB_TXN_BATCH_DETAILS_CT_DEL.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_IOP.Iop_Owner_Hub_Txn_Batch_Details_Ct_Del
(
  hub_txn_batch_detail_id NUMERIC(29) NOT NULL,
  hub_txn_batch_id NUMERIC(29) NOT NULL,
  hub_iop_txn_id NUMERIC(29),
  raw_dr_record_type STRING,
  raw_dr_original_record_type STRING,
  raw_dr_txn_reference_id STRING,
  raw_dr_exit_txn_date STRING,
  raw_dr_facs_id STRING,
  raw_dr_facs_desc STRING,
  raw_dr_exit_plaza STRING,
  raw_dr_exit_plaza_desc STRING,
  raw_dr_exit_lane STRING,
  raw_dr_entry_txn_date STRING,
  raw_dr_entry_plaza STRING,
  raw_dr_entry_plaza_desc STRING,
  raw_dr_entry_lane STRING,
  raw_dr_tag_agency_id STRING,
  raw_dr_tag_serial_number STRING,
  raw_dr_tag_status STRING,
  raw_dr_occupancy_indicator STRING,
  raw_dr_vehicle_class STRING,
  raw_dr_toll_amt STRING,
  raw_dr_discount_plan STRING,
  raw_dr_lic_plate_country STRING,
  raw_dr_lic_plate_state STRING,
  raw_dr_lic_plate_number STRING,
  raw_dr_lic_plate_type STRING,
  raw_dr_vehicle_class_adj_flag STRING,
  raw_dr_sys_matched_flag STRING,
  failed STRING,
  failed_disposition STRING,
  failed_reason STRING,
  failed_disp_status STRING,
  failed_date DATETIME,
  failed_hub_txn_batch_detail_id NUMERIC(29),
  system_error STRING,
  adj_failed_disp_reason_code STRING,
  incorrect_fee_charged STRING,
  acct_id NUMERIC(29),
  acct_bal_before_posting NUMERIC(31, 2),
  acct_bal_after_posting NUMERIC(31, 2),
  raw_dr_adjustment_date STRING,
  raw_dr_adjustment_reason STRING,
  raw_dr_other_adjustment_desc STRING,
  raw_dr_adjustment_count STRING,
  raw_dr_resubmit_reason STRING,
  raw_dr_resubmit_count STRING,
  raw_dr_home_txn_reference_id STRING,
  raw_dr_recon_home_agency_id STRING,
  raw_dr_iop_disposition STRING,
  raw_dr_posted_amt STRING,
  raw_dr_posted_date STRING,
  raw_dr_posted_discount_plan STRING,
  raw_dr_proc_fee_flat STRING,
  raw_dr_proc_fee_pct STRING,
  raw_dr_attribute_1 STRING,
  raw_dr_attribute_2 STRING,
  raw_dr_attribute_3 STRING,
  raw_dr_attribute_4 STRING,
  raw_dr_attribute_5 STRING,
  attribute_6 STRING,
  attribute_7 STRING,
  attribute_8 STRING,
  attribute_9 STRING,
  attribute_10 STRING,
  created_by STRING NOT NULL,
  date_created DATETIME NOT NULL,
  modified_by STRING NOT NULL,
  date_modified DATETIME NOT NULL,
  insert_datetime DATETIME NOT NULL
)
;
