-- Translation time: 2024-06-04T08:01:15.437249Z
-- Translation job ID: a14a1a7f-7d63-47c9-8296-0b7483d5c271
-- Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_LG_IOP/Tables/IOP_OWNER_TXN_RECON_DETAIL_TABLE.sql
-- Translated from: SqlServer
-- Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_LG_IOP.Iop_Owner_Txn_Recon_Detail_Table
(
  org_submission_batch_id NUMERIC(29),
  org_submission_batch_detail_id NUMERIC(29),
  hub_iop_txn_id NUMERIC(29),
  record_type STRING,
  file_name STRING,
  submission_type STRING,
  away_agency_ref_id STRING,
  exit_date DATETIME,
  facs_id STRING,
  facs_desc STRING,
  exit_plaza STRING,
  exit_plaza_desc STRING,
  exit_lane STRING,
  entry_date_time DATETIME,
  entry_plazas STRING,
  entry_plaza_desc STRING,
  entry_lane STRING,
  tag_agency_id STRING,
  tag_serial_nbr STRING,
  tag_status STRING,
  occupancy_ind STRING,
  vehicle_class FLOAT64,
  toll_amount FLOAT64,
  discount_plan STRING,
  lic_plate_country STRING,
  lic_plate_state STRING,
  lic_plate_nbr STRING,
  plate_type STRING,
  veh_class_adjust_flag STRING,
  system_match_flag STRING,
  spare_1 STRING,
  spare_2 STRING,
  spare_3 STRING,
  spare_4 STRING,
  spare_5 STRING,
  is_guaranteed STRING,
  adjustment_datetime DATETIME,
  adjust_reason STRING,
  resubmit_reason STRING,
  other_adjust_desc STRING,
  adjustment_count FLOAT64,
  resubmit_count FLOAT64,
  home_agency_ref_id FLOAT64,
  away_agency STRING,
  home_agency STRING,
  post_status STRING,
  tagstore_posting_status STRING,
  posted_discount_plan STRING,
  accepted_amount FLOAT64,
  rejected_amount FLOAT64,
  system_err_amount FLOAT64,
  error_code STRING,
  posted_date DATETIME,
  fixed_fee FLOAT64,
  fee_percent FLOAT64,
  tag_account_id STRING,
  acct_bal_before_posting NUMERIC(31, 2),
  acct_bal_after_posting NUMERIC(31, 2),
  date_created DATETIME,
  run_datetime DATETIME,
  tag_acct_days_negative NUMERIC(29),
  created_by STRING,
  date_modified DATETIME,
  modified_by STRING,
  org_submission_ack_date DATETIME,
  recon_ack_date DATETIME,
  recon_second_ack_date DATETIME,
  recon_submission_date DATETIME,
  org_submission_ack_code STRING,
  org_submission_record_cnt FLOAT64,
  org_submission_seq_nbr FLOAT64,
  submission_date DATETIME,
  last_update_date DATETIME,
  last_update_type STRING
)
;
