## Translation time: 2024-03-04T06:41:57.683170Z
## Translation job ID: 00dc6676-2c12-444a-b02a-71c7788bdc89
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/EDW_TRIPS/Tables/Stage_UnifiedTransaction_PrevRun.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS EDW_TRIPS_STAGE.UnifiedTransaction_PrevRun
(
  tptripid INT64 NOT NULL,
  custtripid INT64,
  citationid INT64,
  tripdate DATETIME,
  tripdayid INT64 NOT NULL,
  laneid INT64,
  customerid INT64 NOT NULL,
  operationsmappingid INT64 NOT NULL,
  tripidentmethod STRING NOT NULL,
  lanetripidentmethod STRING NOT NULL,
  recordtype STRING NOT NULL,
  tripwith STRING,
  transactionpostingtype STRING NOT NULL,
  tripstageid INT64 NOT NULL,
  tripstagecode STRING NOT NULL,
  tripstatusid INT64 NOT NULL,
  tripstatuscode STRING NOT NULL,
  reasoncode STRING NOT NULL,
  citationstagecode STRING NOT NULL,
  trippaymentstatusid INT64 NOT NULL,
  trippaymentstatusdesc STRING NOT NULL,
  sourcename STRING,
  operationsagency STRING,
  facilitycode STRING,
  vehicleid INT64 NOT NULL,
  vehiclenumber STRING,
  vehiclestate STRING,
  tagrefid STRING,
  tagagency STRING,
  vehicleclass STRING,
  revenuevehicleclass INT64,
  sourceofentry INT64,
  sourcetripid INT64,
  disposition STRING,
  ipstransactionid INT64,
  vesserialnumber INT64,
  showbadaddressflag INT64,
  badaddressflag INT64 NOT NULL,
  nonrevenueflag INT64 NOT NULL,
  businessrulematchedflag INT64 NOT NULL,
  manuallyreviewedflag INT64 NOT NULL,
  oosplateflag INT64 NOT NULL,
  vtollflag INT64,
  classadjustmentflag INT64 NOT NULL,
  rpt_paidvsaea STRING,
  expectedamount NUMERIC(31, 2),
  adjustedexpectedamount NUMERIC(31, 2),
  calcadjustedamount NUMERIC(31, 2) NOT NULL,
  tripwithadjustedamount NUMERIC(31, 2),
  tollamount NUMERIC(31, 2),
  actualpaidamount NUMERIC(31, 2) NOT NULL,
  outstandingamount NUMERIC(31, 2) NOT NULL,
  firstpaiddate DATETIME,
  lastpaiddate DATETIME,
  txnagencyid INT64,
  accountagencyid INT64,
  tp_posteddate DATETIME,
  custtrip_posteddate DATETIME,
  violatedtrip_posteddate DATETIME,
  ut_adjustedexpectedamount NUMERIC(31, 2),
  ut_actualpaidamount NUMERIC(31, 2),
  expectedbase NUMERIC(31, 2),
  expectedpremium NUMERIC(31, 2),
  avitollamount NUMERIC(31, 2),
  pbmtollamount NUMERIC(31, 2),
  originalavitollamount NUMERIC(31, 2),
  originalpbmtollamount NUMERIC(31, 2),
  tp_receivedtollamount NUMERIC(31, 2),
  nraw_fareamount NUMERIC(31, 2),
  nraw_vehicleclass_tagfare NUMERIC(31, 2),
  nraw_vehicleclass_platefare NUMERIC(31, 2),
  tp_vehicleclass_tagfare NUMERIC(31, 2),
  tp_vehicleclass_platefare NUMERIC(31, 2),
  tsa_receivedtollamount NUMERIC(31, 2),
  violatedtrippayment_totaltxnamount NUMERIC(31, 2),
  violatedtrippayment_adjustedamount NUMERIC(31, 2),
  violatedtrippayment_actualpaidamount NUMERIC(31, 2),
  ut_tollamount NUMERIC(31, 2),
  tp_tollamount NUMERIC(31, 2),
  custtrip_tollamount NUMERIC(31, 2),
  violatedtrip_tollamount NUMERIC(31, 2),
  tp_outstandingamount NUMERIC(31, 2),
  custtrip_outstandingamount NUMERIC(31, 2),
  violatedtrip_outstandingamount NUMERIC(31, 2),
  tp_tripstatusid INT64,
  custtrip_tripstatusid INT64,
  violatedtrip_tripstatusid INT64,
  tp_tripstageid INT64,
  custtrip_tripstageid INT64,
  violatedtrip_tripstageid INT64,
  tp_paymentstatusid INT64,
  custtrip_paymentstatusid INT64,
  violatedtrip_paymentstatusid INT64,
  ttt_recordtype STRING,
  lnd_updatedate DATETIME,
  edw_updatedate DATETIME,
  backupdate DATETIME
)
;