CREATE TABLE [History].[TP_Customer_Addresses] (
    [CustAddressID] bigint NOT NULL, 
    [CustomerID] bigint NOT NULL, 
    [AddressType] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [AddressLine1] varchar(150) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [AddressLine2] varchar(150) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [AddressLine3] varchar(150) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [City] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [State] varchar(5) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Country] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Zip1] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [Zip2] varchar(4) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [IsActive] bit NOT NULL, 
    [IsCommunication] bit NOT NULL, 
    [CreatedDate] datetime2(3) NOT NULL, 
    [CreatedUser] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [UpdatedDate] datetime2(3) NOT NULL, 
    [UpdatedUser] varchar(50) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [HistID] bigint NOT NULL, 
    [Action] varchar(128) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [IsValid] bit NOT NULL, 
    [ReasonCode] varchar(500) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [AddressUpdatedDate] datetime2(3) NULL, 
    [IsAddressUpdateNotified] bit NULL, 
    [IsValidUpdatedDate] datetime2(3) NULL, 
    [IsSkiptraced] bit NULL, 
    [AddressSourceID] int NULL, 
    [RovSourceID] bigint NULL, 
    [RovSourceType] varchar(10) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [SubSource] varchar(128) COLLATE Latin1_General_100_CI_AS_KS_WS NULL, 
    [MovedToHistoryDate] datetime2(3) NULL, 
    [ICNID] bigint NULL, 
    [ChannelID] int NULL, 
    [LND_UpdateDate] datetime2(3) NULL, 
    [LND_UpdateType] varchar(1) COLLATE Latin1_General_100_CI_AS_KS_WS NULL
)
WITH (CLUSTERED INDEX ( [CustomerID] DESC ), DISTRIBUTION = HASH([CustomerID]));
