TRUNCATE TABLE LND_TBOS_SUPPORT.CDC_Full_Load_Config;

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (100,"FINANCE_ADJUSTMENTS__ct","LND_TBOS_Qlik","Finance_Adjustments","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_Adjustments","LND_TBOS","AdjustmentID","adjustmentid,customerid,accstatusid,amount,adjustmentcategory,txntypeid,adjustmentdate,drcrflag,adjustmentreason,ismanualentry,approvedstatusid,approvedstatusdate,paymentid,icnid,locationid,sourceid,sourcename,tolladjustmentid,comments,newadjustmentid,iscreditcardtype,sourcetranstypeid,sourcertdid,refundrequestid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (101,"FINANCE_ADJUSTMENT_LINEITEMS__ct","LND_TBOS_Qlik","Finance_Adjustment_LineItems","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_Adjustment_LineItems","LND_TBOS","AdjLineItemID","adjlineitemid,adjustmentid,amount,apptxntypecode,linkid,linksourcename,newtollamount,vehicleclass,laneid,isvisible,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (102,"FINANCE_GlDailySummaryByCoaIdBuId__ct","LND_TBOS_Qlik","Finance_GlDailySummaryByCoaIDBuID","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_GlDailySummaryByCoaIDBuID","LND_TBOS","ChartOfAccountID, BusinessUnitID, PostedDate","dailysummaryid,chartofaccountid,businessunitid,beginningbal,debittxnamount,credittxnamount,endingbal,posteddate,fiscalyearname,jobrundate,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS_Finance_GL",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (103,"FINANCE_GL_TRANSACTIONS__ct","LND_TBOS_Qlik","Finance_Gl_Transactions","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_Gl_Transactions","LND_TBOS","Gl_TxnID","gl_txnid,postingdate,postingdate_yyyymm,customerid,txntypeid,businessprocessid,linkid,linksourcename,txndate,txnamount,iscontra,description,requestid,businessunitid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS_Finance_GL",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (104,"FINANCE_GL_TXN_LINEITEMS__ct","LND_TBOS_Qlik","Finance_Gl_Txn_LineItems","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_Gl_Txn_LineItems","LND_TBOS","PK_ID","pk_id,gl_txnid,description,chartofaccountid,debitamount,creditamount,specialjournalid,drcr_flag,txntype_li_id,txntypeid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS_Finance_GL",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (105,"FINANCE_TXNTYPES__ct","LND_TBOS_Qlik","Finance_TxnTypes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_TxnTypes","LND_TBOS","TxnTypeID","txntypeid,txntype,txndesc,txntype_categoryid,statementnote,customernote,violatornote,isautomatic,adjustmentcategoryid,levelid,status,levelcode,businessunitid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (106,"HISTORY_TP_CUSTOMERS__ct","LND_TBOS_Qlik","History_History_TP_Customers","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","History_TP_Customers","LND_TBOS","HistID","histid,customerid,usertypeid,customerstatusid,accountstatusid,accountstatusdate,parentcustomerid,sourceofentry,revenuecategoryid,isprimary,sourcepkid,action,agencyid,regcustrefid,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (107,"HISTORY_TP_CUSTOMER_ATTRIBUTES__ct","LND_TBOS_Qlik","History_History_TP_Customer_Attributes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","History_TP_Customer_Attributes","LND_TBOS","HistID","histid,customerid,driverlicencenumber,driverlicenceapprovedstate,driverlicenceexpirationdate,autoreplenishmentid,preferredshipment,transponderpurchasemethod,calculatedrebillamount,thresholdamount,ismanualhold,statementdeliveryoptionid,sourceofchannelid,rebill_hold_starteffectivedate,rebill_hold_endeffectivedate,is_notifications_added,capamount,kycstatusid,kycstatusdate,statementcycleid,rebillstatus,rebilldate,preferredlanguage,ishearingimpairment,isfrequentcaller,issupervisor,tagsinstatusfile,invoiceintervalid,invoiceamount,invoiceday,lowbalanceamount,mbsgenerationday,ssn,is_commercial,iseventsponsor,isvip,ismilitary,autorecalcreplamt,nonrevenuetypeid,istollperks,ismarketingandnewsletter,isdirectcarrierbilling,companycode,isgroundtransportation,mbsimageid,violatortypeid,icnid,channelid,action,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (108,"IOP_BOS_IOP_OUTBOUNDTRANSACTIONS__ct","LND_TBOS_Qlik","IOP_BOS_IOP_OutboundTransactions","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","IOP_BOS_IOP_OutboundTransactions","LND_TBOS","BOSIOPTransactionID","bosioptransactionid,iopid,transactiontypeid,tagtype,transactiondate,agencyid,entryplaza,entrylane,tagstatus,licencenumber,licensestate,exitplaza,exitlane,transactionstatus,reconcilitionfileid,tollamount,acceptedamount,iscorrected,discountamount,tptripid,tagserialnumber,vehicleclass,tripmethod,posteddate,resubmitcount,tranfileid,facilitycode,plazacode,lanecode,entrytripdatetime,exittripdatetime,platetype,facilitydesc,entryplazadesc,exitplazadesc,entrytripdatetimewithtimezone,exittripdatetimewithtimezone,licenseplatecountry,violationserialnumber,vestimestamp,tagagencyid,resubmitreasoncode,correctionreasoncode,transactionflatfee,transactionpercentfee,sourceofentry,correctioncount,sourcepkid,recordcode,accountagencyid,adjustmentdatetime,postingdisposition,postingdispositionreason,adjustmentresponsepayload,homeagencyrefid,spare1,spare2,spare3,spare4,spare5,othercorrectiondescription,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (109,"RBAC_LocationRoles__ct","LND_TBOS_Qlik","Rbac_LocationRoles","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Rbac_LocationRoles","LND_TBOS","LocationRoleID","locationroleid,locationid,roleid,channelid,icnid,isactive,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (110,"TER_ViolatorCollectionsOutbound__ct","LND_TBOS_Qlik","TER_ViolatorCollectionsOutbound","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TER_ViolatorCollectionsOutbound","LND_TBOS","VioCollOutboundID","viocolloutboundid,fileid,recordtype,violatorid,invoicenumber,mbsid,firstname,lastname,address1,address2,city,state,zipcode,mobilephonenumber,workphonenumber,invoiceamount,tollamount,feeamount,paymentorcreditadjustment,reversalorcharge,totalamountdue,nsfindicator,nsfdate,zcinvoicedate,firstnnpdate,secondnnpdate,thirdnnpdate,vehiclenumber,vehiclestate,vehiclemake,vehiclemodel,vehiclecolor,vehicleyear,hastsatransactions,rentalcarindicator,recalldate,lastactivityoninvoice,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (111,"TOLLPLUS_AGENCIES__ct","LND_TBOS_Qlik","TOLLPLUS_TollPlus_Agencies","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Agencies","LND_TBOS","AgencyID","agencyid,agencytypeid,agencyname,agencycode,agencydesc,ifsccode,accounttype,bankname,accountname,accountnumber,rangeid,startfacilitycode,endfacilitycode,tagcount,customerid,starthexid,endhexid,revcode,encryptflag,pgpkeyid,ftpurl,ftplogin,ftppwd,isactive,starteffectivedate,endeffectivedate,isswitchable,protocoltype,ishomeagency,parentagencycode,iopagencyid,hubid,tagagencyid,channelid,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (112,"TOLLPLUS_Channels__ct","LND_TBOS_Qlik","TollPlus_Channels","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Channels","LND_TBOS","ChannelID","channelid,channelname,isdisplay,channeldesc,isactive,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (113,"TOLLPLUS_CustomerFlagReferenceLookup__ct","LND_TBOS_Qlik","TollPlus_CustomerFlagReferenceLookup","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_CustomerFlagReferenceLookup","LND_TBOS","CustomerFlagReferenceID","customerflagreferenceid,flagname,flagdescription,isactive,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (114,"TOLLPLUS_ICN__ct","LND_TBOS_Qlik","TollPlus_ICN","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_ICN","LND_TBOS","ICNID","icnid,userid,cashamount,checkamount,creditamount,moamount,floatamount,icnstatus,isdayshiftclosed,cashiercheckamount,shiftstartdate,shiftenddate,locationid,locationroleid,retrycnt,stickertagscount,integratedtagscount,licenseplatetagscount,hardcasetagscount,shiftapprovalstatus,shiftsubmitted,reasoncode,csrcashamount,createddate,createduser,updateduser,updateddate,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (115,"TOLLPLUS_INVOICE_CHARGES_TRACKER__ct","LND_TBOS_Qlik","TollPlus_Invoice_Charges_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Invoice_Charges_Tracker","LND_TBOS","InvoiceChargeID","invoicechargeid,invoiceid,invbatchid,amount,feecode,paymentstatusid,outstandingamount,iswriteoff,icnid,writeoffdate,writeoffamount,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (116,"TOLLPLUS_INVOICE_HEADER__ct","LND_TBOS_Qlik","TollPlus_Invoice_Header","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Invoice_Header","LND_TBOS","InvoiceID","invoiceid,invoicenumber,masterinvoiceid,invoicedate,duedate,startperiod,endperiod,customerid,vehicleid,stagestepid,previousdue,totalamount,amountpaid,balancedue,invoicestatus,currentcharges,adjustedamount,isviolator,invbatchid,inv_file_path,unbilledamt,overpmtamt,servicetax,is_hold,ispdfgenerated,agencyid,graceperioddate,mailingdate,agestageid,currentchargestoll,currentchargesfee,nonpaymentfee,invoiceadjamt,invoiceaccountstatus,previousduestartperiod,previousdueendperiod,mailreturndate,isdiscountprocessed,unpaidtripcnt,collectionstatus,sourceid,sourcename,unpaidtripamount,sourcewriteoff,channelid,icnid,citationstatus,secntvdate,sourceinvoicestatus,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (117,"TOLLPLUS_INVOICE_LINEITEMS__ct","LND_TBOS_Qlik","TollPlus_Invoice_LineItems","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Invoice_LineItems","LND_TBOS","InvLineItemID","invlineitemid,invoiceid,linkid,custtxncategory,txntype,stmt_literal,amount,subsystem,linksourcename,txndate,referenceinvoiceid,sourceviolationstatus,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (118,"TOLLPLUS_LANES__ct","LND_TBOS_Qlik","TollPlus_Lanes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Lanes","LND_TBOS","LaneID","laneid,lanecode,plazaid,lanename,lanetype,description,lanestatus,direction,lanecategoryid,exitlanecode,channelid,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (119,"TOLLPLUS_LOCATIONS__ct","LND_TBOS_Qlik","TollPlus_Locations","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Locations","LND_TBOS","LocationID","locationid,locationcode,locationname,description,isowned,isnonrevenue,countyname,courtname,agencyid,ishvenabled,istsa,agencytsasubscribermapid,tsafacilityid,channelid,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (120,"TOLLPLUS_MbsHeader__ct","LND_TBOS_Qlik","TollPlus_Mbsheader","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Mbsheader","LND_TBOS","MbsID","mbsid,mbsgenerateddate,ispresentmbs,startperiod,endperiod,duedate,customerid,vehicleid,vehiclestate,previousdue,amountpaid,adjustments,currentchargestoll,currentchargesfee,totalamount,plateimagepath,pdfpath,mailingdate,mailreturndate,emaileddate,emailreturndate,newduedate,sourcepkid,mbsstatusid,qacategory,platefilepathconfigurationid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (121,"TOLLPLUS_MbsInvoices__ct","LND_TBOS_Qlik","TollPlus_MbsInvoices","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_MbsInvoices","LND_TBOS","MbsInvoicesID","mbsinvoicesid,mbsid,invoiceid,agestageid,invoicenumber,invaddedreasonid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (122,"TOLLPLUS_PLANS__ct","LND_TBOS_Qlik","TollPlus_Plans","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Plans","LND_TBOS","PlanID","planid,planname,plancode,plandescription,parentid,isfeerequired,istagrequired,statementcycleid,starteffectivedate,endeffectivedate,invoiceintervalid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (123,"TOLLPLUS_PLAZAS__ct","LND_TBOS_Qlik","TollPlus_Plazas","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Plazas","LND_TBOS","PlazaID","plazaid,plazacode,locationid,plazaname,description,ipaddress,portnumber,agencyid,pricemode,transactionfeemode,chartofaccountid,ftpurl,pgpkeyid,ftplogin,ftppwd,encryptflag,accountnumber,accounttype,accountname,bankname,ifsccode,transactiontype,isowned,isnonrevenue,plazatypeid,exitplazacode,channelid,icnid,parkingtaxrate,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (124,"TOLLPLUS_REF_INVOICE_WORKFLOW_STAGES__ct","LND_TBOS_Qlik","TollPlus_Ref_Invoice_Workflow_Stages","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Ref_Invoice_Workflow_Stages","LND_TBOS","StageID","stageid,stagename,stageorder,stepscount,isactive,stagecode,agingperiod,graceperiod,waiveallfees,applyavirate,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (125,"TOLLPLUS_REF_LOOKUPTYPECODES_HIERARCHY__ct","LND_TBOS_Qlik","TollPlus_Ref_LookupTypeCodes_Hierarchy","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_Ref_LookupTypeCodes_Hierarchy","LND_TBOS","LookupTypeCodeID","lookuptypecodeid,lookuptypecode,lookuptypecodedesc,parent_lookuptypecodeid,is_available_foruse,remarks,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (126,"TOLLPLUS_TOLLSCHEDULEDTL__ct","LND_TBOS_Qlik","TollPlus_TollScheduleDtl","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TollScheduleDtl","LND_TBOS","TollScheduleDtlID","tollscheduledtlid,tollschedulehdrid,tollrateid,channelid,icnid,fromtime,totime,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (127,"TOLLPLUS_TOLLSCHEDULEHDR__ct","LND_TBOS_Qlik","TollPlus_TollScheduleHdr","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TollScheduleHdr","LND_TBOS","TollScheduleHdrID","tollschedulehdrid,entrylaneid,entryplazaid,exitplazaid,channelid,icnid,starteffectivedate,endeffectivedate,tollschedulehdrdesc,transactiontype,transactionmenthod,scheduletype,isactive,`interval`,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (128,"TOLLPLUS_TP_APPLICATION_PARAMETERS__ct","LND_TBOS_Qlik","TollPlus_TP_AppLication_Parameters","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_AppLication_Parameters","LND_TBOS","ParameterID","parameterid,parameterkey,parametername,parametervalue,parameterdesc,measurementdesc,configtype,departmenttype,datatype,minlength,maxlength,allowedsplchars,isspaceallowed,regularexp,starteffectivedate,endeffectivedate,iseditable,channelid,icnid,isactive,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (129,"TOLLPLUS_TP_CUSTOMERS__ct","LND_TBOS_Qlik","TollPlus_TP_Customers","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customers","LND_TBOS","CustomerID","customerid,usertypeid,customerstatusid,accountstatusid,accountstatusdate,parentcustomerid,sourceofentry,revenuecategoryid,isprimary,sourcepkid,agencyid,regcustrefid,lastactivitytimestamp,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (130,"TOLLPLUS_TP_CUSTOMERTRIPS__ct","LND_TBOS_Qlik","TollPlus_TP_CustomerTrips","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_CustomerTrips","LND_TBOS","CustTripID","custtripid,tptripid,customerid,entry_tolltxnid,exit_tolltxnid,entrytripdatetime,exittripdatetime,tripidentmethod,tripchargetype,entrylaneid,entryplazaid,exitlaneid,exitplazaid,vehiclenumber,vehiclestate,vehicleclass,vehicleid,tagrefid,tollamount,feeamounts,discountsamount,outstandingamount,tripstageid,tripstatusid,tripstatusdate,posteddate,paymentstatusid,tagtype,transactiontypeid,rewards_discountamount,platetype,disposition,pbmtollamount,avitollamount,licenseplatecountry,locationid,agencyid,netamount,tagagency,isrovwaiting,sourceofentry,accountagencyid,ttxn_id,isexcessivevtoll,transactionpostingtype,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (131,"TOLLPLUS_TP_CUSTOMER_ACCSTATUS_TRACKER__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_AccStatus_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_AccStatus_Tracker","LND_TBOS","AccStatusHistID","accstatushistid,customerid,accountstatusid,accountstatusdate,parent_accstatushistid,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (132,"TOLLPLUS_TP_CUSTOMER_ADDRESSES__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Addresses","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Addresses","LND_TBOS","CustAddressID","custaddressid,customerid,addresstype,addressline1,addressline2,addressline3,city,state,country,zip1,zip2,isactive,iscommunication,isvalid,reasoncode,addressupdateddate,isaddressupdatenotified,isvalidupdateddate,isskiptraced,addresssourceid,rovsourceid,rovsourcetype,subsource,action,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (133,"TOLLPLUS_TP_CUSTOMER_ATTRIBUTES__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Attributes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Attributes","LND_TBOS","CustomerID","customerid,driverlicencenumber,driverlicenceapprovedstate,driverlicenceexpirationdate,autoreplenishmentid,preferredshipment,transponderpurchasemethod,calculatedrebillamount,thresholdamount,ismanualhold,statementdeliveryoptionid,sourceofchannelid,rebill_hold_starteffectivedate,rebill_hold_endeffectivedate,is_notifications_added,capamount,kycstatusid,kycstatusdate,statementcycleid,rebillstatus,rebilldate,preferredlanguage,ishearingimpairment,isfrequentcaller,issupervisor,tagsinstatusfile,invoiceintervalid,invoiceamount,invoiceday,lowbalanceamount,mbsgenerationday,ssn,is_commercial,iseventsponsor,isvip,ismilitary,autorecalcreplamt,nonrevenuetypeid,istollperks,ismarketingandnewsletter,isdirectcarrierbilling,companycode,isgroundtransportation,mbsimageid,violatortypeid,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (134,"TOLLPLUS_TP_CUSTOMER_BALANCES__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Balances","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Balances","LND_TBOS","CustbalID","custbalid,customerid,balancedate,balanceamount,balancetype,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (135,"TOLLPLUS_TP_CUSTOMER_BALANCE_ALERT_FACTS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Balance_Alert_Facts","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Balance_Alert_Facts","LND_TBOS","CustomerID","customerid,lowbalanceflag,lowbalancedate,negbalanceflag,negbalancedate,lowbalancenotice,negativebalancenotice,sentemailcount,regionalioplowbalanceflag,regionalioplowbalancedate,nationalioplowbalanceflag,nationalioplowbalancedate,accountfinancialstatus,balanceflag,balancenotice,balancedate,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (136,"TOLLPLUS_TP_CUSTOMER_BUSINESS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Business","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Business","LND_TBOS","CustomerID","customerid,organisationname,isfleet,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (137,"TOLLPLUS_TP_CUSTOMER_CONTACTS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Contacts","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Contacts","LND_TBOS","CustomerID","contactid,customerid,title,suffix,firstname,middlename,lastname,gender,nametype,iscommunication,dateofbirth,firstname2,lastname2,icnid,channelid,race,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (138,"TOLLPLUS_TP_CUSTOMER_FLAGS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Flags","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Flags","LND_TBOS","CustomerFlagID","customerflagid,customerid,customerflagreferenceid,flagvalue,startdate,enddate,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (139,"TOLLPLUS_TP_CUSTOMER_LOGINS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Logins","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Logins","LND_TBOS","LoginID","loginid,customerid,icnid,channelid,username,password,last_logindate,last_pwd_modifieddate,current_pwd_expirydate,pwd_attempts_count,pinnumber,islocked,createddate,createduser,updateddate,updateduser,sq_attemptcount,sq_lockouttime,lockouttime,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (140,"TOLLPLUS_TP_CUSTOMER_PHONES__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Phones","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Phones","LND_TBOS","CustPhoneID","custphoneid,customerid,phonetype,phonenumber,extention,isactive,iscommunication,isverified,isbadphone,issolicitphone,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (141,"TOLLPLUS_TP_CUSTOMER_PLANS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Plans","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Plans","LND_TBOS","CustPlanID","custplanid,customerid,planid,starteffectivedate,endeffectivedate,icnid,channelid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (142,"TOLLPLUS_TP_CUSTOMER_TAGS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Tags","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Tags","LND_TBOS","CustTagID","custtagid,customerid,tagstartdate,tagenddate,tagtype,tagstatus,tagalias,hextagid,serialno,returnedorassignedtype,itemcode,isnonrevenue,isgroundtransportation,tagagency,specialitytag,mounting,isdfwblocked,isdalblocked,tagassigneddate,tagstatusdate,channelid,icnid,tagassignedenddate,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (143,"TOLLPLUS_TP_CUSTOMER_TRIP_CHARGES_TRACKER__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Trip_Charges_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Trip_Charges_Tracker","LND_TBOS","TripChargeID","tripchargeid,custtripid,amount,amountclass,paymentstatusid,outstandingamount,customerid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (144,"TOLLPLUS_TP_CUSTOMER_VEHICLES__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Vehicles","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Vehicles","LND_TBOS","VehicleID","vehicleid,customerid,vehiclenumber,vehiclecountry,vehiclestate,year,make,model,color,starteffectivedate,endeffectivedate,vehiclestatusid,vehicleclasscode,vin,isprotected,isexempted,istempnumber,tagid,contractualtypeid,platetype,vehicleshape,fuelefficiency,ishamradiooperator,istrailer,licenseplateimagepath,departmentname,excessivevtolls,isinhv,isvrh,docno,vehiclebodyvin,county,temp_source,temp_pk,temp_key,channelid,icnid,isvtollenabled,filepathconfigurationid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (145,"TOLLPLUS_TP_IMAGE_REVIEW_RESULTS__ct","LND_TBOS_Qlik","TollPlus_TP_Image_Review_Results","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Image_Review_Results","LND_TBOS","ImageReviewResultID","imagereviewresultid,sourcetransactionid,ipstransactionid,facilitycode,plazacode,lanecode,timestamp,vesserialnumber,disposition,reasoncode,ismanuallyreviewed,platetype,plateregistration,platejurisdiction,platejurisdictioncountry,sourcelanvilationid,sourcevilationid,imagecodeoff,imagereviewcount,createduser,createddate,updateduser,updateddate,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (146,"TOLLPLUS_TP_INVOICE_RECEIPTS_TRACKER__ct","LND_TBOS_Qlik","TollPlus_TP_Invoice_Receipts_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Invoice_Receipts_Tracker","LND_TBOS","ReceiptID","receiptid,invoiceid,invoice_chargeid,invbatchid,amountreceived,linkid,linksourcename,txndate,overpaymentid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (147,"TOLLPLUS_TP_TOLLRATE_DTLS__ct","LND_TBOS_Qlik","TollPlus_TP_TollRate_Dtls","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_TollRate_Dtls","LND_TBOS","TollRateDtlID","tollratedtlid,tollrateid,vehicleclass,lanetype,tollamount,channelid,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (148,"TOLLPLUS_TP_TOLLRATE_HDR__ct","LND_TBOS_Qlik","TollPlus_TP_TollRate_Hdr","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_TollRate_Hdr","LND_TBOS","TollRateHdrID","tollratehdrid,tollratename,isactive,transactionmenthod,vehicleclasstype,channelid,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (149,"TOLLPLUS_TP_TRIPS__ct","LND_TBOS_Qlik","TollPlus_TP_Trips","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Trips","LND_TBOS","TpTripID","tptripid,entry_tolltxnid,exit_tolltxnid,entrytripdatetime,entrytripdatetimeutc,exittripdatetime,exittripdatetimeutc,tripidentmethod,tripchargetype,entrylaneid,entryplazaid,exitlaneid,exitplazaid,lanetype,vehiclenumber,vehicleid,vehiclestate,vehicleclass,tagrefid,tollamount,receivedtollamount,feeamounts,discountsamount,outstandingamount,tripstageid,tripstatusid,tripstatusdate,posteddate,irtripid,paymentstatusid,reasoncode,sourcetripid,tagvehicleclass,tagtype,transactiontypeid,platetype,ipstransactionid,pbmtollamount,avitollamount,originalpbmtollamount,originalavitollamount,licenseplatecountry,locationid,agencyid,disposition,receiveddate,tagagency,tagagencyid,sourceofentry,accountagencyid,isimagereviewed,sourcetxnid,linkid,tripwith,isnonrevenue,txnrate,transactionpostingtype,sourceid,sourcename,acct_id,ttxn_id,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (150,"TOLLPLUS_TP_VIOLATEDTRIPS__ct","LND_TBOS_Qlik","TollPlus_TP_ViolatedTrips","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_ViolatedTrips","LND_TBOS","CitationID","citationid,tptripid,violatorid,vehiclenumber,vehiclestate,vehicleclass,vehicleid,tollamount,feeamounts,outstandingamount,citationstage,citationtype,entrylaneid,exitlaneid,entryplazaid,exitplazaid,tripstageid,tripstatusid,tripstatusdate,stagemodifieddate,entrytripdatetime,exittripdatetime,paymentstatusid,transactiontypeid,platetype,agencyid,pbmtollamount,avitollamount,licenseplatecountry,locationid,custrefid,isimmediateflag,netamount,sourceofentry,accountagencyid,acct_id,violation_id,violation_status,isexcessivevtoll,transactionpostingtype,iswriteoff,writeoffdate,writeoffamount,createddate,createduser,updateddate,updateduser,posteddate,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (151,"TOLLPLUS_TP_VIOLATED_TRIP_CHARGES_TRACKER__ct","LND_TBOS_Qlik","TollPlus_TP_Violated_Trip_Charges_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Violated_Trip_Charges_Tracker","LND_TBOS","TripChargeID","tripchargeid,citationid,violatorid,amount,amountclass,trippaymentstatusid,outstandingamount,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (152,"TOLLPLUS_TP_VIOLATED_TRIP_RECEIPTS_TRACKER__ct","LND_TBOS_Qlik","TollPlus_TP_Violated_Trip_Receipts_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Violated_Trip_Receipts_Tracker","LND_TBOS","TripReceiptID","tripreceiptid,citationid,violatorid,linkid,amountreceived,txndate,linksourcename,tripchargeid,invoiceid,overpaymentid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (153,"TOLLPLUS_TRIPSTAGES__ct","LND_TBOS_Qlik","TollPlus_TripStages","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TripStages","LND_TBOS","TripStageID","tripstageid,tripstagecode,tripstagedescription,parentstageid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (154,"TOLLPLUS_TRIPSTATUSES__ct","LND_TBOS_Qlik","TollPlus_TripStatuses","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TripStatuses","LND_TBOS","TripStatusID","tripstatusid,tripstatuscode,tripstatusdescription,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (155,"TRANPROCESSING_NttaRawTransactions__ct","LND_TBOS_Qlik","TranProcessing_NTTARawTransactions","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TranProcessing_NTTARawTransactions","LND_TBOS","TxnID","txnid,sourcesystem,metadatarecordtype,metadatapublishtime,metadatarecordnumber,recordtype,recordnumber,timestamp,facilitycode,plazacode,lane,logontimestamp,lanemode,revenuevehicleclass,revenueaxles,indicatedvehicleclass,indicatedaxles,forwardaxles,reverseaxles,vehiclespeed,fareamount,straddleindication,entryloopactivation,midlaneloopactivation,exitloopactivation,imagerequested,paymenttype,tagidnumber,tagagency,tagstatus,tagclass,iagtagvehicletype,iagtagvehicleaxles,iagtagvehicleweight,iagtagdualreartires,iagtagrevenuetype,iagtagcommissionflag,tagreads,violationserialnumber,vestimestamp,standbymodestatus,acmstatus,avireaderstatus,dualtiresensor,failovermodulestatus,redundantlcstatus,avcstatus,treadlestatus,scannerseparatorstatus,vesstatus,attendantterminalstatus,facilityserveravistatusdownload,facilityservertransactionupload,ups,digitaliointerface,receiptprinter,tvlbatchid,faretableid,taglowbattery,estimatedaxlecount,auxiliaryloopactivation,maintenanceoverride,rawstringdata,isunabletoparse,ismalformed,hostbosid,disposition,invoicestatus,equipmentcode,deviceinstance,statuscode,conditionstate,messagetext,logofftimestamp,tagtimestamp,tagstring,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (156,"TRANPROCESSING_TSARawTransactions__ct","LND_TBOS_Qlik","TranProcessing_TSARawTransactions","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TranProcessing_TSARawTransactions","LND_TBOS","TxnID","txnid,transactiontype,recordtype,subscriberuniquetransactionid,resubmittalreason,resubmittalcount,authorityid,locationtype,facility,subscriberid,entryinformation,plaza,lane,lanemode,transactiondate,transactiontime,transponderid,transponderstatus,transpondervalidationlistfilename,licenseplatevalidationlistfilename,vehicleclassification,axlesexpected,axlescounted,speed,hovdesignation,exitbarrierorgantryinformation,collectorid,vaultid,vehicleclassificationfortolldetermination,transpondertollamount,transponderdiscounttype,discountedtranspondertollamount,videotollamountwithoutvideotollpremium,videotollamountwithvideotollpremium,videodiscounttype,discountedvideotollamountwithoutvideotollpremium,discountedvideotollamountwithvideotollpremium,cashtollamount,cashdiscounttype,discountedcashtollamount,amountpaid,unusualoccurrencecode,numberofimages,hostbosid,fileid,sourcepkid,ismalformed,isunabletoparse,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (157,"TSA_TSATripAttributes__ct","LND_TBOS_Qlik","TSA_TSATripAttributes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TSA_TSATripAttributes","LND_TBOS","TTpTripID","ttptripid,tptripid,subscriberuniquetransactionid,authorityid,subscriberid,transponderid,collectorid,vaultid,validtxnprimarykeyid,sourcetripid,sourcepkid,transactiontype,recordtype,resubmittalreason,resubmittalcount,locationtype,facility,entryinformation,plaza,lane,lanemode,transactiondate,transactiontime,transponderstatus,transpondervalidationlistfilename,licenseplatevalidationlistfilename,vehicleclassification,axlesexpected,axlescounted,speed,hovdesignation,exitbarrierorgantryinformation,vehicleclassificationfortolldetermination,transpondertollamount,transponderdiscounttype,discountedtranspondertollamount,videotollamountwithoutvideotollpremium,videotollamountwithvideotollpremium,videodiscounttype,discountedvideotollamountwithoutvideotollpremium,discountedvideotollamountwithvideotollpremium,cashtollamount,cashdiscounttype,discountedcashtollamount,amountpaid,unusualoccurrencecode,numberofimages,transactionstatus,disposition,lastvalidrecordcount,originaltransactiontype,postedamount,correctioncount,originalexittransactiondatetime,bmsalertdate,pbmtollamount,avitollamount,invoicestatus,rejectreason,basefee,variablefee,interoptransactionfee,netpayamount,subscriberidfromfile,calculatedvideoamtwithvideopremium,calculateddiscountedvideoamtwithvideopremium,revenuedate,createddate,updateddate,createduser,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (158,"TollPlus_TP_CustTxns__ct","LND_TBOS_Qlik","TollPlus_TP_CustTxns","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_CustTxns","LND_TBOS","CustTxnID","custtxnid,customerid,linkid,linksourcename,txnamount,posteddate,vehicleid,apptxntypecode,businessprocesscode,stmt_literal,custtxncategory,previousbalance,currentbalance,subsystem,locationname,balancetype,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (159,"FINANCE_BUSINESSPROCESSES__ct","LND_TBOS_Qlik","Finance_BusinessProcesses","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_BusinessProcesses","LND_TBOS","BusinessProcessID","businessprocessid,businessprocesscode,businessprocessdescription,status,isavailable,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (160,"FINANCE_CHARTOFACCOUNTS__ct","LND_TBOS_Qlik","Finance_ChartOfAccounts","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_ChartOfAccounts","LND_TBOS","ChartOfAccountID","surrogate_coaid,chartofaccountid,accountname,parentchartofaccountid,agcode,asgcode,lowerbound,upperbound,status,iscontrolaccount,normalbalancetype,legalaccountid,agencycode,starteffectivedate,endeffectivedate,comments,isdeleted,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (161,"FINANCE_PAYMENTTXN_LINEITEMS__ct","LND_TBOS_Qlik","Finance_PaymentTxn_LineItems","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_PaymentTxn_LineItems","LND_TBOS","LineItemID","lineitemid,paymentid,apptxntypecode,lineitemamount,linkid,linksourcename,customerid,paymentdate,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (162,"FINANCE_PAYMENTTXNS__ct","LND_TBOS_Qlik","Finance_PaymentTxns","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_PaymentTxns","LND_TBOS","PaymentID","paymentid,paymentdate,voucherno,subsystem,paymentmodeid,intiatedby,activitytype,statementnote,txnamount,paymentstatusid,refpaymentid,reftype,sourcepkid,accountstatusid,approvedby,channelid,locationid,sourceofentry,reasontext,icnid,isvirtualcheck,pmttxntype,sourcepmtid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (163,"TOLLPLUS_SUBSYSTEMS__ct","LND_TBOS_Qlik","TollPlus_SubSystems","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_SubSystems","LND_TBOS","SubSystemID","subsystemid,subsystemname,subsystemcode,subsystemdescription,parentsubsystemid,iswebdisplay,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (164,"TOLLPLUS_APPTXNTYPES__ct","LND_TBOS_Qlik","TollPlus_AppTxnTypes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_AppTxnTypes","LND_TBOS","apptxntypeid","apptxntypeid,apptxntypecode,apptxntypedesc,effected_balancetype_positive,effected_balancetype_negative,main_balance_type,txntype_categoryid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (165,"TOLLPLUS_TP_CUSTOMER_TRIP_RECEIPTS_TRACKER__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Trip_Receipts_Tracker","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Trip_Receipts_Tracker","LND_TBOS","TripReceiptID","tripreceiptid,customerid,linkid,amountreceived,txndate,custtripid,linksourcename,tripchargeid,invoiceid,overpaymentid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (166,"TOLLPLUS_TP_CUSTOMER_VEHICLE_TAGS__ct","LND_TBOS_Qlik","TollPlus_TP_Customer_Vehicle_Tags","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TP_Customer_Vehicle_Tags","LND_TBOS","VehicleTagID","vehicletagid,vehicleid,custtagid,isblocklisted,starteffectivedate,endeffectivedate,channelid,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (167,"TOLLPLUS_TXNTYPE_CATEGORIES__ct","LND_TBOS_Qlik","TollPlus_TxnType_Categories","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_TxnType_Categories","LND_TBOS","CategoryID","categoryid,categoryname,categorydesc,status,parent_categoryid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (168,"FINANCE_REFUNDREQUESTS_QUEUE__ct","LND_TBOS_Qlik","Finance_RefundRequests_Queue","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","Finance_RefundRequests_Queue","LND_TBOS","RefundRequestID","refundrequestid,exceptionrrid,customerid,refundrequeststate,refundrequesttype,subsystem,txntypeid,paytypeid,originalpaytypeid,amount,paymenttxnid,requesteddate,processeddate,reason,approveddate,approvedby,retrycnt,icnid,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);

INSERT INTO LND_TBOS_SUPPORT.CDC_Full_Load_Config(table_id,source_table_name,source_dataset_name,stage_table_name,stage_cdc_dataset_name,stage_full_dataset_name,target_table_name,target_dataset_name,key_column,target_table_columns_list,cdc_run_flag,fullload_run_flag,cdc_batch_name,batch_window)
VALUES (169,"TOLLPLUS_ZipCodes__ct","LND_TBOS_Qlik","TollPlus_ZipCodes","LND_TBOS_STAGE_CDC","LND_TBOS_STAGE_FULL","TollPlus_ZipCodes","LND_TBOS","zipcode","zipcode,city,county,state,txdotid,isadminhearing,createddate,createduser,updateddate,updateduser,lnd_updatedate,lnd_updatetype,src_changedate","N","N","TRIPS",3);


