CREATE TABLE  IF NOT EXISTS LND_LG_TS.Tag_Owner_Account_Tag_History_Ct_Ins (
    acct_id NUMERIC(29),
    acct_tag_seq INT64,
    tag_history_seq INT64,
    acct_tag_status STRING,
    assigned_date DATETIME,
    expired_date DATETIME,
    lic_plate STRING,
    lic_state STRING,
    lic_plate_tag STRING,
    vehicle_descr STRING,
    vehicle_make STRING,
    vehicle_model STRING,
    vehicle_year STRING,
    vehicle_color STRING,
    vehicle_class_code STRING,
    tag_id STRING,
    date_created DATETIME,
    created_by STRING,
    agency_id STRING,
    vpn_id FLOAT64,
    unit_id STRING,
    insert_datetime DATETIME NOT NULL
);