CREATE TABLE IF NOT EXISTS LND_LG_TS.Tag_Owner_Activity_Summaries (
    activity_date DATETIME NOT NULL,
    amex_receipts_store NUMERIC(33, 4) NOT NULL,
    amex_receipts_online NUMERIC(33, 4) NOT NULL,
    amex_refunds_store NUMERIC(33, 4) NOT NULL,
    amex_autocharge_rebill NUMERIC(33, 4) NOT NULL,
    amex_chargeback_store NUMERIC(33, 4) NOT NULL,
    disc_receipts_store NUMERIC(33, 4) NOT NULL,
    disc_receipts_online NUMERIC(33, 4) NOT NULL,
    disc_refunds_store NUMERIC(33, 4) NOT NULL,
    disc_autocharge_rebill NUMERIC(33, 4) NOT NULL,
    disc_chargeback_store NUMERIC(33, 4) NOT NULL,
    mc_receipts_store NUMERIC(33, 4) NOT NULL,
    mc_receipts_online NUMERIC(33, 4) NOT NULL,
    mc_refunds_store NUMERIC(33, 4) NOT NULL,
    mc_autocharge_rebill NUMERIC(33, 4) NOT NULL,
    mc_chargeback_store NUMERIC(33, 4) NOT NULL,
    visa_receipts_store NUMERIC(33, 4) NOT NULL,
    visa_receipts_online NUMERIC(33, 4) NOT NULL,
    visa_refunds_store NUMERIC(33, 4) NOT NULL,
    visa_autocharge_rebill NUMERIC(33, 4) NOT NULL,
    visa_chargeback_store NUMERIC(33, 4) NOT NULL,
    cash_receipts_store NUMERIC(33, 4) NOT NULL,
    check_receipts_store NUMERIC(33, 4) NOT NULL,
    mo_receipts_store NUMERIC(33, 4) NOT NULL,
    check_refunds_store NUMERIC(33, 4) NOT NULL,
    total_cash_receipts NUMERIC(33, 4) NOT NULL,
    total_credit_receipts NUMERIC(33, 4) NOT NULL,
    total_refunds NUMERIC(33, 4) NOT NULL,
    total_rebills NUMERIC(33, 4) NOT NULL,
    net_daily_total NUMERIC(33, 4) NOT NULL,
    diner_receipts_store NUMERIC(33, 4) NOT NULL,
    diner_receipts_online NUMERIC(33, 4) NOT NULL,
    diner_refunds_store NUMERIC(33, 4) NOT NULL,
    diner_autocharge_rebill NUMERIC(33, 4) NOT NULL,
    diner_chargeback_store NUMERIC(33, 4) NOT NULL,
    check_refunds_rebill NUMERIC(33, 4) NOT NULL,
    credit_refunds_rebill NUMERIC(33, 4) NOT NULL,
    acct_type_code STRING NOT NULL,
    last_update_type STRING NOT NULL,
    last_update_date DATETIME NOT NULL
);