## Translation time: 2024-03-13T05:19:34.327071Z
## Translation job ID: 0a711804-adbe-4db7-8cda-d8808bd4ce52
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/NTTA_Missing_DDLs/LND_TBOS_dbo_Bankruptcy.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS.dbo_Bankruptcy
(
  deliveryroutingid STRING NOT NULL,
  recordtype STRING,
  primarydebtorind STRING,
  primaryssn STRING,
  primaryfirstname STRING,
  primarymiddlename STRING,
  primarylastname STRING,
  primarysuffixname STRING,
  primaryaka1 STRING,
  primaryaka2 STRING,
  primaryaddress1 STRING,
  primaryaddress2 STRING,
  primarycity STRING,
  primarystate STRING,
  primaryzip STRING,
  secondarydebtorind STRING,
  secondaryssn STRING,
  secondaryfirstname STRING,
  secondarymiddlename STRING,
  secondarylastname STRING,
  secondarysuffix STRING,
  secondaryaka1 STRING,
  secondaryaka2 STRING,
  secondaryaddress1 STRING,
  secondaryaddress2 STRING,
  secondarycity STRING,
  secondarystate STRING,
  secondaryzip STRING,
  filedate STRING,
  chapter STRING,
  casenumber STRING,
  petitionseqnumber STRING,
  joint STRING,
  prose STRING,
  bankruptcycourtnumberlegacy STRING,
  bankruptcycourtnumbernew STRING,
  courtname STRING,
  courtphonenumber STRING,
  courtaddress1 STRING,
  courtaddress2 STRING,
  courtcity STRING,
  courtstate STRING,
  courtzip STRING,
  courtdistrictcode STRING,
  courtdivisioncode STRING,
  lawfirm STRING,
  attorneyname STRING,
  attorneyphone STRING,
  attorneyaddress1 STRING,
  attorneyaddress2 STRING,
  attorneycity STRING,
  attorneystate STRING,
  attorneyzip STRING,
  trusteename STRING,
  trusteephone STRING,
  trusteeaddress1 STRING,
  trusteeaddress2 STRING,
  trusteecity STRING,
  trusteestate STRING,
  trusteezip STRING,
  `341date` STRING,
  accountnumber STRING,
  accountnumberdebtorindicator STRING,
  filler1 STRING,
  filler2 STRING,
  accountdateopen STRING,
  filler3 STRING,
  updatestatus STRING,
  changedate STRING,
  transfercomments STRING,
  datareportingsource STRING,
  filler5 STRING,
  filler6 STRING,
  ediuniquedocumentid STRING,
  filler7 STRING,
  filler8 STRING,
  filler9 STRING,
  recordcreationdate STRING,
  lnd_updatedate DATETIME,
  src_changedate DATETIME
)
;