## Translation time: 2024-03-04T06:44:00.523569Z
## Translation job ID: a86d938d-fa65-424d-bf4e-0008985e1778
## Source: ntta-gcp-poc-source-code-scripts/APS1_DDLs_latest/LND_TBOS/Tables/EIP_Transactions.sql
## Translated from: SqlServer
## Translated to: BigQuery

CREATE TABLE IF NOT EXISTS LND_TBOS.EIP_Transactions
(
  transactionid INT64 NOT NULL,
  agencycode STRING NOT NULL,
  serverid STRING NOT NULL,
  plazaid STRING NOT NULL,
  laneid STRING NOT NULL,
  tranid STRING NOT NULL,
  laneposition STRING,
  issuingauthority STRING,
  timestamp INT64,
  utctimestamp DATETIME,
  localtimestamp DATETIME,
  transactiondate DATE NOT NULL,
  transactiontime INT64 NOT NULL,
  transponderid STRING,
  transponderclass STRING,
  vehicleclass STRING,
  vehiclelength STRING,
  violationcode STRING,
  tollclass INT64,
  tolldue INT64,
  tollpaid INT64,
  imageofrecordid INT64 NOT NULL,
  primaryplateimageid INT64,
  primaryplatereadconfidence INT64,
  ocrplateregistration STRING,
  registrationreadconfidence INT64,
  ocrplatejurisdiction STRING,
  jurisdictionreadconfidence INT64,
  signaturehandle STRING,
  signatureconfidence INT64,
  combinedplateresultstatus INT64,
  combinedstateresultstatus INT64,
  startdate DATETIME NOT NULL,
  enddate DATETIME,
  stagetypeid INT64,
  stageid INT64,
  statusid INT64,
  statusdescription STRING,
  statusdate DATETIME,
  vehicleid INT64,
  groupid INT64,
  representativesigimageid INT64 NOT NULL,
  signaturematchid INT64 NOT NULL,
  signatureconflictid1 INT64 NOT NULL,
  signatureconflictid2 INT64 NOT NULL,
  daynighttwilight INT64,
  node STRING NOT NULL,
  nodeinst STRING NOT NULL,
  roadwayid INT64 NOT NULL,
  agencytimestamp INT64 NOT NULL,
  receiveddate DATETIME NOT NULL,
  auditfileid INT64,
  misreaddisposition INT64,
  disposition INT64,
  reasoncode INT64,
  lastreviewer STRING,
  platetypeprefix STRING,
  platetypesuffix STRING,
  plateregistration STRING,
  platejurisdiction STRING,
  isfserialnumber INT64,
  revenueaxles INT64,
  indicatedvehicleclass INT64,
  indicatedaxles INT64,
  actualaxles INT64,
  vehiclespeed INT64,
  tagstatus INT64,
  facilitycode STRING,
  platetype STRING,
  subscriberid STRING,
  createddate DATETIME NOT NULL,
  createduser STRING,
  updateddate DATETIME,
  updateduser STRING,
  lnd_updatedate DATETIME,
  lnd_updatetype STRING,
  src_changedate DATETIME
)
CLUSTER BY
transactionid
;